apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# You need to create these secrets in your overlay
# secretGenerator:
#   - name: ironic-credentials
#     files:
#     - username=ironic-username
#     - password=ironic-password
#   - name: ironic-inspector-credentials
#     files:
#     - username=ironic-inspector-username
#     - password=ironic-inspector-password

patches:
  - path: credentials_patch.yaml
    target:
      kind: Deployment
      name: controller-manager
