apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
kind: ControllerManagerConfig
health:
  healthProbeBindAddress: :9440
metrics:
  bindAddress: 127.0.0.1:8085
webhook:
  port: 9443
leaderElection:
  leaderElect: true
  resourceName: a9498140.metal3.io
