# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
## Main branch config starts here
- package-ecosystem: "github-actions"
  directory: "/" # Location of package manifests
  schedule:
    interval: "monthly"
    day: "saturday"
  target-branch: main
  ## group all action bumps into single PR
  groups:
    github-actions:
      patterns: ["*"]
  ignore:
  # Ignore major bumps in main, as it breaks the group bump process
  - dependency-name: "*"
    update-types: ["version-update:semver-major"]
  commit-message:
    prefix: ":seedling:"
  labels:
  - "ok-to-test"
  # Go
- package-ecosystem: "gomod"
  directories:
  - "/"
  - "/apis"
  - "/hack/tools"
  - "/pkg/hardwareutils"
  - "/test"
  schedule:
    interval: "weekly"
    day: "sunday"
  target-branch: main
  groups:
    kubernetes:
      patterns: ["k8s.io/*"]
    capi:
      patterns: ["sigs.k8s.io/cluster-api", "sigs.k8s.io/cluster-api/test"]
  ignore:
  # Ignore controller-runtime major and minor bumps as its upgraded manually.
  - dependency-name: "sigs.k8s.io/controller-runtime"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  # Ignore k8s major and minor bumps and its transitives modules
  - dependency-name: "k8s.io/*"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - dependency-name: "sigs.k8s.io/controller-tools"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  commit-message:
    prefix: ":seedling:"
  labels:
  - "ok-to-test"
## Main branch config ends here

## release-0.10 branch config starts here
- package-ecosystem: "github-actions"
  directory: "/" # Location of package manifests
  schedule:
    interval: "monthly"
    day: "saturday"
  target-branch: release-0.10
  ## group all action bumps into single PR
  groups:
    github-actions:
      patterns: ["*"]
  ignore:
  # Ignore major and minor bumps for release branch
  - dependency-name: "*"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  commit-message:
    prefix: ":seedling:"
  labels:
  - "ok-to-test"
  # Go
- package-ecosystem: "gomod"
  directories:
  - "/"
  - "/apis"
  - "/hack/tools"
  - "/pkg/hardwareutils"
  - "/test"
  schedule:
    interval: "weekly"
    day: "sunday"
  target-branch: release-0.10
  groups:
    kubernetes:
      patterns: ["k8s.io/*"]
    capi:
      patterns: ["sigs.k8s.io/cluster-api", "sigs.k8s.io/cluster-api/test"]
  ignore:
  # golang.org/x/* only releases minors no patches, so minors have to be allowed
  - dependency-name: "golang.org/x/*"
    update-types: ["version-update:semver-major"]
  - dependency-name: "*"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  commit-message:
    prefix: ":seedling:"
  labels:
  - "ok-to-test"

## release-0.10 branch config ends here

## release-0.9 branch config starts here
- package-ecosystem: "github-actions"
  directory: "/" # Location of package manifests
  schedule:
    interval: "monthly"
    day: "saturday"
  target-branch: release-0.9
  ## group all action bumps into single PR
  groups:
    github-actions:
      patterns: ["*"]
  ignore:
  # Ignore major and minor bumps for release branch
  - dependency-name: "*"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  commit-message:
    prefix: ":seedling:"
  labels:
  - "ok-to-test"
  # Go
- package-ecosystem: "gomod"
  directories:
  - "/"
  - "/apis"
  - "/hack/tools"
  - "/pkg/hardwareutils"
  - "/test"
  schedule:
    interval: "weekly"
    day: "sunday"
  target-branch: release-0.9
  groups:
    kubernetes:
      patterns: ["k8s.io/*"]
    capi:
      patterns: ["sigs.k8s.io/cluster-api", "sigs.k8s.io/cluster-api/test"]
  ignore:
  # golang.org/x/* only releases minors no patches, so minors have to be allowed
  - dependency-name: "golang.org/x/*"
    update-types: ["version-update:semver-major"]
  - dependency-name: "*"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  commit-message:
    prefix: ":seedling:"
  labels:
  - "ok-to-test"

## release-0.9 branch config ends here
