run:
  go: "1.23"
  build-tags:
  - e2e
  - vbmctl
linters:
  disable-all: true
  enable:
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  #- containedctx
  - copyloopvar
  - decorder
  - dogsled
  #- dupl
  - dupword
  - durationcheck
  - errcheck
  - errchkjson
  #- errname
  #- errorlint
  #- exhaustive
  - exptostd
  - fatcontext
  #- forbidigo
  #- forcetypeassert
  - gci
  - ginkgolinter
  - gocheckcompilerdirectives
  - gochecksumtype
  - goconst
  - gocritic
  - godot
  - gofmt
  - goimports
  - goprintffuncname
  - gosec
  - gosimple
  - gosmopolitan
  - govet
  - iface
  - importas
  - ineffassign
  - intrange
  - loggercheck
  - makezero
  - mirror
  - misspell
  #- mnd
  - nakedret
  - nilerr
  - nilnesserr
  #- nilnil
  - noctx
  - nolintlint
  - nosprintfhostport
  #- perfsprint
  - prealloc
  - predeclared
  - reassign
  - revive
  - rowserrcheck
  - staticcheck
  - stylecheck
  #- tagliatelle
  - testifylint
  - thelper
  - tparallel
  - typecheck
  - unconvert
  - unparam
  - unused
  - usestdlibvars
  - usetesting
  - whitespace
  # Run with --fast=false for more extensive checks
  fast: true
linters-settings:
  gosec:
    severity: medium
    confidence: medium
    concurrency: 8
  importas:
    no-unaliased: true
    alias:
    # Kubernetes
    - pkg: k8s.io/api/core/v1
      alias: corev1
    - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
      alias: apiextensionsv1
    - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
      alias: metav1
    - pkg: k8s.io/apimachinery/pkg/api/errors
      alias: k8serrors
    - pkg: k8s.io/apimachinery/pkg/util/errors
      alias: kerrors
    - pkg: k8s.io/component-base/logs/api/v1
      alias: logsv1
    # Controller Runtime
    - pkg: sigs.k8s.io/controller-runtime
      alias: ctrl
    # BMO
    - pkg: github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1
      alias: metal3api
  nolintlint:
    allow-unused: false
    require-specific: true
  gocritic:
    enabled-tags:
    - experimental
    disabled-checks:
    - appendAssign
    - dupImport # https://github.com/go-critic/go-critic/issues/845
    - evalOrder
    - ifElseChain
    - octalLiteral
    - regexpSimplify
    - sloppyReassign
    - truncateCmp
    - typeDefFirst
    - unnamedResult
    - unnecessaryDefer
    - whyNoLint
    - wrapperFunc
issues:
  exclude-dirs:
  - mock*
  exclude-files:
  - "zz_generated.*\\.go$"
  - ".*conversion.*\\.go$"
  exclude-rules:
  - path: test/e2e
    linters:
    - gosec
  - path: test/e2e
    linters:
    - goconst
  - path: _test\.go
    linters:
    - gci
    - goconst
    - gosec
  - path: _test\.go
    linters:
    - errcheck
    - gci
    - noctx
    - revive
    - stylecheck
    - unparam
    - unused
  # Specific exclude rules for deprecated fields that are still part of the codebase.
  # These should be removed as the referenced deprecated item is removed from the project.
  - linters:
    - staticcheck
    text: "SA1019:"
  # Disable linters for conversion
  - linters:
    - staticcheck
    text: "SA1019:"
    path: .*(api|types)\/.*\/conversion.*\.go$
  # Dot imports for gomega or ginkgo are allowed
  # within test files.
  - path: _test\.go
    text: should not use dot imports
  - path: (test|e2e)/.*.go
    text: should not use dot imports
  - linters:
    - revive
    text: "exported: exported method .*\\.(Reconcile|SetupWithManager|SetupWebhookWithManager) should have comment or be unexported"
  # Exclude some packages or code to require comments, for example test code, or fake clients.
  - linters:
    - revive
    text: exported (method|function|type|const) (.+) should have comment or be unexported
    source: (func|type).*Fake.*
  - linters:
    - revive
    text: exported (method|function|type|const) (.+) should have comment or be unexported
    path: fake_\.go
  - linters:
    - revive
    text: exported (method|function|type|const) (.+) should have comment or be unexported
    path: .*(api|types)\/.*\/conversion.*\.go$
  - linters:
    - revive
    text: "var-naming: don't use underscores in Go names;"
    path: .*(api|types)\/.*\/conversion.*\.go$
  - linters:
    - revive
    text: "receiver-naming: receiver name"
    path: .*(api|types)\/.*\/conversion.*\.go$
  - linters:
    - stylecheck
    text: "ST1003: should not use underscores in Go names;"
    path: .*(api|types)\/.*\/conversion.*\.go$
  - linters:
    - stylecheck
    text: "ST1016: methods on the same type should have the same receiver name"
    path: .*(api|types)\/.*\/conversion.*\.go$
  include:
  - EXC0002 # include "missing comments" issues from golangci-lint
  max-issues-per-linter: 0
  max-same-issues: 0
