# Force dep to vendor the code generators, which aren't imported just used at dev time.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
  "github.com/pkg/errors",
  "github.com/gophercloud/gophercloud",
  "github.com/gophercloud/utils/openstack/baremetal/v1/nodes",
]

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.1"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.14.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.1"

[[override]]
  name = "k8s.io/client-go"
  version = "v11.0.0"

[[override]]
  name = "github.com/coreos/prometheus-operator"
  version = "=v0.30.0"

[[constraint]]
  name = "sigs.k8s.io/controller-runtime"
  version = "=v0.2.0-beta.2"

[[override]]
  name = "sigs.k8s.io/controller-tools"
  revision = "9d55346c2bde73fb3326ac22eac2e5210a730207"

[[constraint]]
  name = "github.com/gophercloud/gophercloud"
  revision = "157432124aab520975efedb5e54b95287785578d"

# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"
  version="v1.4.7"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  source = "https://github.com/estroz/operator-sdk.git"
  branch = "bump-controller-runtime-v0.2.0"

[prune]
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    non-go = false
