apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: baremetal-operator-manager-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: baremetal-operator-manager-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: baremetal-operator-manager-clusterrole
subjects:
- kind: ServiceAccount
  name: baremetal-operator-controller-manager
  namespace: baremetal-operator-system
---
