/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	metal3apiv1beta1 "github.com/metal3-io/baremetal-operator/apis/metal3.io/v1beta1"
	"sigs.k8s.io/controller-runtime/pkg/conversion"
)

// v1alpha1 is a spoke version. v1beta1 is the hub (storage version).
//
// The mechanical field-by-field conversion is generated by conversion-gen into
// zz_generated.conversion.go (regenerate with `make generate`).
//
// Following the pattern used by cluster-api-provider-metal3, cluster-api and
// cluster-api-provider-openstack, ConvertTo/ConvertFrom additionally use the
// conversion-data annotation (MarshalData/UnmarshalData, defined locally in
// conversion_data.go) to make the round-trip lossless.
//
// The annotation stores a snapshot of the HUB object on the SPOKE, so that
// hub-only fields (fields that exist in v1beta1 but not v1alpha1) survive a
// hub -> spoke -> hub round-trip:
//
//   - ConvertFrom (hub -> spoke) calls MarshalData to stash the hub snapshot in
//     an annotation on the spoke.
//   - ConvertTo (spoke -> hub) calls UnmarshalData to restore any previously
//     stashed hub-only fields onto the freshly converted hub object.

// --- BareMetalHost ---

// ConvertTo converts this BareMetalHost (v1alpha1) to the Hub version (v1beta1).
func (src *BareMetalHost) ConvertTo(dstRaw conversion.Hub) error {
	dst := dstRaw.(*metal3apiv1beta1.BareMetalHost)
	if err := Convert_v1alpha1_BareMetalHost_To_v1beta1_BareMetalHost(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// ConvertFrom converts the Hub version (v1beta1) to this BareMetalHost (v1alpha1).
func (dst *BareMetalHost) ConvertFrom(srcRaw conversion.Hub) error {
	src := srcRaw.(*metal3apiv1beta1.BareMetalHost)
	if err := Convert_v1beta1_BareMetalHost_To_v1alpha1_BareMetalHost(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// --- HardwareData ---

// ConvertTo converts this HardwareData (v1alpha1) to the Hub version (v1beta1).
func (src *HardwareData) ConvertTo(dstRaw conversion.Hub) error {
	dst := dstRaw.(*metal3apiv1beta1.HardwareData)
	if err := Convert_v1alpha1_HardwareData_To_v1beta1_HardwareData(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// ConvertFrom converts the Hub version (v1beta1) to this HardwareData (v1alpha1).
func (dst *HardwareData) ConvertFrom(srcRaw conversion.Hub) error {
	src := srcRaw.(*metal3apiv1beta1.HardwareData)
	if err := Convert_v1beta1_HardwareData_To_v1alpha1_HardwareData(src, dst, nil); err != nil {
		return err
	}
	return nil
}
