/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	metal3apiv1beta1 "github.com/metal3-io/baremetal-operator/apis/metal3.io/v1beta1"
	apimachineryconversion "k8s.io/apimachinery/pkg/conversion"
	"sigs.k8s.io/controller-runtime/pkg/conversion"
)

// v1alpha1 is a spoke version. v1beta1 is the hub (storage version).
//
// The mechanical field-by-field conversion is generated by conversion-gen into
// zz_generated.conversion.go (regenerate with `make generate`).
//
// Following the pattern used by cluster-api-provider-metal3, cluster-api and
// cluster-api-provider-openstack, ConvertTo/ConvertFrom additionally use the
// conversion-data annotation (MarshalData/UnmarshalData, defined locally in
// conversion_data.go) to make the round-trip lossless.
//
// The annotation stores a snapshot of the HUB object on the SPOKE, so that
// hub-only fields (fields that exist in v1beta1 but not v1alpha1) survive a
// hub -> spoke -> hub round-trip:
//
//   - ConvertFrom (hub -> spoke) calls MarshalData to stash the hub snapshot in
//     an annotation on the spoke.
//   - ConvertTo (spoke -> hub) calls UnmarshalData to restore any previously
//     stashed hub-only fields onto the freshly converted hub object.

// --- BareMetalHost ---

// ConvertTo converts this BareMetalHost (v1alpha1) to the Hub version (v1beta1).
func (src *BareMetalHost) ConvertTo(dstRaw conversion.Hub) error {
	dst := dstRaw.(*metal3apiv1beta1.BareMetalHost)
	if err := Convert_v1alpha1_BareMetalHost_To_v1beta1_BareMetalHost(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// ConvertFrom converts the Hub version (v1beta1) to this BareMetalHost (v1alpha1).
func (dst *BareMetalHost) ConvertFrom(srcRaw conversion.Hub) error {
	src := srcRaw.(*metal3apiv1beta1.BareMetalHost)
	if err := Convert_v1beta1_BareMetalHost_To_v1alpha1_BareMetalHost(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// --- BareMetalSwitch ---

// ConvertTo converts this BareMetalSwitch (v1alpha1) to the Hub version (v1beta1).
func (src *BareMetalSwitch) ConvertTo(dstRaw conversion.Hub) error {
	dst := dstRaw.(*metal3apiv1beta1.BareMetalSwitch)
	if err := Convert_v1alpha1_BareMetalSwitch_To_v1beta1_BareMetalSwitch(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// ConvertFrom converts the Hub version (v1beta1) to this BareMetalSwitch (v1alpha1).
func (dst *BareMetalSwitch) ConvertFrom(srcRaw conversion.Hub) error {
	src := srcRaw.(*metal3apiv1beta1.BareMetalSwitch)
	if err := Convert_v1beta1_BareMetalSwitch_To_v1alpha1_BareMetalSwitch(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// --- BMCEventSubscription ---

// ConvertTo converts this BMCEventSubscription (v1alpha1) to the Hub version (v1beta1).
func (src *BMCEventSubscription) ConvertTo(dstRaw conversion.Hub) error {
	dst := dstRaw.(*metal3apiv1beta1.BMCEventSubscription)
	if err := Convert_v1alpha1_BMCEventSubscription_To_v1beta1_BMCEventSubscription(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// ConvertFrom converts the Hub version (v1beta1) to this BMCEventSubscription (v1alpha1).
func (dst *BMCEventSubscription) ConvertFrom(srcRaw conversion.Hub) error {
	src := srcRaw.(*metal3apiv1beta1.BMCEventSubscription)
	if err := Convert_v1beta1_BMCEventSubscription_To_v1alpha1_BMCEventSubscription(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// --- DataImage ---

// ConvertTo converts this DataImage (v1alpha1) to the Hub version (v1beta1).
func (src *DataImage) ConvertTo(dstRaw conversion.Hub) error {
	dst := dstRaw.(*metal3apiv1beta1.DataImage)
	if err := Convert_v1alpha1_DataImage_To_v1beta1_DataImage(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// ConvertFrom converts the Hub version (v1beta1) to this DataImage (v1alpha1).
func (dst *DataImage) ConvertFrom(srcRaw conversion.Hub) error {
	src := srcRaw.(*metal3apiv1beta1.DataImage)
	if err := Convert_v1beta1_DataImage_To_v1alpha1_DataImage(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// --- FirmwareSchema ---

// ConvertTo converts this FirmwareSchema (v1alpha1) to the Hub version (v1beta1).
func (src *FirmwareSchema) ConvertTo(dstRaw conversion.Hub) error {
	dst := dstRaw.(*metal3apiv1beta1.FirmwareSchema)
	if err := Convert_v1alpha1_FirmwareSchema_To_v1beta1_FirmwareSchema(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// ConvertFrom converts the Hub version (v1beta1) to this FirmwareSchema (v1alpha1).
func (dst *FirmwareSchema) ConvertFrom(srcRaw conversion.Hub) error {
	src := srcRaw.(*metal3apiv1beta1.FirmwareSchema)
	if err := Convert_v1beta1_FirmwareSchema_To_v1alpha1_FirmwareSchema(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// --- HardwareData ---

// ConvertTo converts this HardwareData (v1alpha1) to the Hub version (v1beta1).
func (src *HardwareData) ConvertTo(dstRaw conversion.Hub) error {
	dst := dstRaw.(*metal3apiv1beta1.HardwareData)
	if err := Convert_v1alpha1_HardwareData_To_v1beta1_HardwareData(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// ConvertFrom converts the Hub version (v1beta1) to this HardwareData (v1alpha1).
func (dst *HardwareData) ConvertFrom(srcRaw conversion.Hub) error {
	src := srcRaw.(*metal3apiv1beta1.HardwareData)
	if err := Convert_v1beta1_HardwareData_To_v1alpha1_HardwareData(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// --- HostClaim ---

// ConvertTo converts this HostClaim (v1alpha1) to the Hub version (v1beta1).
func (src *HostClaim) ConvertTo(dstRaw conversion.Hub) error {
	dst := dstRaw.(*metal3apiv1beta1.HostClaim)
	if err := Convert_v1alpha1_HostClaim_To_v1beta1_HostClaim(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// ConvertFrom converts the Hub version (v1beta1) to this HostClaim (v1alpha1).
func (dst *HostClaim) ConvertFrom(srcRaw conversion.Hub) error {
	src := srcRaw.(*metal3apiv1beta1.HostClaim)
	if err := Convert_v1beta1_HostClaim_To_v1alpha1_HostClaim(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// --- HostDeployPolicy ---

// ConvertTo converts this HostDeployPolicy (v1alpha1) to the Hub version (v1beta1).
func (src *HostDeployPolicy) ConvertTo(dstRaw conversion.Hub) error {
	dst := dstRaw.(*metal3apiv1beta1.HostDeployPolicy)
	if err := Convert_v1alpha1_HostDeployPolicy_To_v1beta1_HostDeployPolicy(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// ConvertFrom converts the Hub version (v1beta1) to this HostDeployPolicy (v1alpha1).
func (dst *HostDeployPolicy) ConvertFrom(srcRaw conversion.Hub) error {
	src := srcRaw.(*metal3apiv1beta1.HostDeployPolicy)
	if err := Convert_v1beta1_HostDeployPolicy_To_v1alpha1_HostDeployPolicy(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// --- HostFirmwareComponents ---

// ConvertTo converts this HostFirmwareComponents (v1alpha1) to the Hub version (v1beta1).
func (src *HostFirmwareComponents) ConvertTo(dstRaw conversion.Hub) error {
	dst := dstRaw.(*metal3apiv1beta1.HostFirmwareComponents)
	if err := Convert_v1alpha1_HostFirmwareComponents_To_v1beta1_HostFirmwareComponents(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// ConvertFrom converts the Hub version (v1beta1) to this HostFirmwareComponents (v1alpha1).
func (dst *HostFirmwareComponents) ConvertFrom(srcRaw conversion.Hub) error {
	src := srcRaw.(*metal3apiv1beta1.HostFirmwareComponents)
	if err := Convert_v1beta1_HostFirmwareComponents_To_v1alpha1_HostFirmwareComponents(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// --- HostFirmwareSettings ---

// ConvertTo converts this HostFirmwareSettings (v1alpha1) to the Hub version (v1beta1).
func (src *HostFirmwareSettings) ConvertTo(dstRaw conversion.Hub) error {
	dst := dstRaw.(*metal3apiv1beta1.HostFirmwareSettings)
	if err := Convert_v1alpha1_HostFirmwareSettings_To_v1beta1_HostFirmwareSettings(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// ConvertFrom converts the Hub version (v1beta1) to this HostFirmwareSettings (v1alpha1).
func (dst *HostFirmwareSettings) ConvertFrom(srcRaw conversion.Hub) error {
	src := srcRaw.(*metal3apiv1beta1.HostFirmwareSettings)
	if err := Convert_v1beta1_HostFirmwareSettings_To_v1alpha1_HostFirmwareSettings(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// --- HostNetworkAttachment ---

// ConvertTo converts this HostNetworkAttachment (v1alpha1) to the Hub version (v1beta1).
func (src *HostNetworkAttachment) ConvertTo(dstRaw conversion.Hub) error {
	dst := dstRaw.(*metal3apiv1beta1.HostNetworkAttachment)
	if err := Convert_v1alpha1_HostNetworkAttachment_To_v1beta1_HostNetworkAttachment(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// ConvertFrom converts the Hub version (v1beta1) to this HostNetworkAttachment (v1alpha1).
func (dst *HostNetworkAttachment) ConvertFrom(srcRaw conversion.Hub) error {
	src := srcRaw.(*metal3apiv1beta1.HostNetworkAttachment)
	if err := Convert_v1beta1_HostNetworkAttachment_To_v1alpha1_HostNetworkAttachment(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// --- HostUpdatePolicy ---

// ConvertTo converts this HostUpdatePolicy (v1alpha1) to the Hub version (v1beta1).
func (src *HostUpdatePolicy) ConvertTo(dstRaw conversion.Hub) error {
	dst := dstRaw.(*metal3apiv1beta1.HostUpdatePolicy)
	if err := Convert_v1alpha1_HostUpdatePolicy_To_v1beta1_HostUpdatePolicy(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// ConvertFrom converts the Hub version (v1beta1) to this HostUpdatePolicy (v1alpha1).
func (dst *HostUpdatePolicy) ConvertFrom(srcRaw conversion.Hub) error {
	src := srcRaw.(*metal3apiv1beta1.HostUpdatePolicy)
	if err := Convert_v1beta1_HostUpdatePolicy_To_v1alpha1_HostUpdatePolicy(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// --- PreprovisioningImage ---

// ConvertTo converts this PreprovisioningImage (v1alpha1) to the Hub version (v1beta1).
func (src *PreprovisioningImage) ConvertTo(dstRaw conversion.Hub) error {
	dst := dstRaw.(*metal3apiv1beta1.PreprovisioningImage)
	if err := Convert_v1alpha1_PreprovisioningImage_To_v1beta1_PreprovisioningImage(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// ConvertFrom converts the Hub version (v1beta1) to this PreprovisioningImage (v1alpha1).
func (dst *PreprovisioningImage) ConvertFrom(srcRaw conversion.Hub) error {
	src := srcRaw.(*metal3apiv1beta1.PreprovisioningImage)
	if err := Convert_v1beta1_PreprovisioningImage_To_v1alpha1_PreprovisioningImage(src, dst, nil); err != nil {
		return err
	}
	return nil
}

// --- Manually provided conversions ---
//
// SchemaSettingError is an internal error helper (it implements the error
// interface) and is never serialized as part of any Spec or Status. Its two
// fields are unexported, so conversion-gen emits only autoConvert_* no-ops and
// no public Convert_* wrappers. RegisterConversions still references the public
// wrappers, so we provide them here delegating to the generated no-ops.

// Convert_v1alpha1_SchemaSettingError_To_v1beta1_SchemaSettingError converts between the two error helper types.
func Convert_v1alpha1_SchemaSettingError_To_v1beta1_SchemaSettingError(in *SchemaSettingError, out *metal3apiv1beta1.SchemaSettingError, s apimachineryconversion.Scope) error {
	return autoConvert_v1alpha1_SchemaSettingError_To_v1beta1_SchemaSettingError(in, out, s)
}

// Convert_v1beta1_SchemaSettingError_To_v1alpha1_SchemaSettingError converts between the two error helper types.
func Convert_v1beta1_SchemaSettingError_To_v1alpha1_SchemaSettingError(in *metal3apiv1beta1.SchemaSettingError, out *SchemaSettingError, s apimachineryconversion.Scope) error {
	return autoConvert_v1beta1_SchemaSettingError_To_v1alpha1_SchemaSettingError(in, out, s)
}
