//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1beta1 "github.com/metal3-io/baremetal-operator/apis/metal3.io/v1beta1"
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Accelerator)(nil), (*v1beta1.Accelerator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Accelerator_To_v1beta1_Accelerator(a.(*Accelerator), b.(*v1beta1.Accelerator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Accelerator)(nil), (*Accelerator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Accelerator_To_v1alpha1_Accelerator(a.(*v1beta1.Accelerator), b.(*Accelerator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppliedNetworkAttachmentConfig)(nil), (*v1beta1.AppliedNetworkAttachmentConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppliedNetworkAttachmentConfig_To_v1beta1_AppliedNetworkAttachmentConfig(a.(*AppliedNetworkAttachmentConfig), b.(*v1beta1.AppliedNetworkAttachmentConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.AppliedNetworkAttachmentConfig)(nil), (*AppliedNetworkAttachmentConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AppliedNetworkAttachmentConfig_To_v1alpha1_AppliedNetworkAttachmentConfig(a.(*v1beta1.AppliedNetworkAttachmentConfig), b.(*AppliedNetworkAttachmentConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BIOS)(nil), (*v1beta1.BIOS)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BIOS_To_v1beta1_BIOS(a.(*BIOS), b.(*v1beta1.BIOS), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.BIOS)(nil), (*BIOS)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_BIOS_To_v1alpha1_BIOS(a.(*v1beta1.BIOS), b.(*BIOS), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BMCDetails)(nil), (*v1beta1.BMCDetails)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BMCDetails_To_v1beta1_BMCDetails(a.(*BMCDetails), b.(*v1beta1.BMCDetails), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.BMCDetails)(nil), (*BMCDetails)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_BMCDetails_To_v1alpha1_BMCDetails(a.(*v1beta1.BMCDetails), b.(*BMCDetails), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BareMetalHost)(nil), (*v1beta1.BareMetalHost)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BareMetalHost_To_v1beta1_BareMetalHost(a.(*BareMetalHost), b.(*v1beta1.BareMetalHost), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.BareMetalHost)(nil), (*BareMetalHost)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_BareMetalHost_To_v1alpha1_BareMetalHost(a.(*v1beta1.BareMetalHost), b.(*BareMetalHost), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BareMetalHostList)(nil), (*v1beta1.BareMetalHostList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BareMetalHostList_To_v1beta1_BareMetalHostList(a.(*BareMetalHostList), b.(*v1beta1.BareMetalHostList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.BareMetalHostList)(nil), (*BareMetalHostList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_BareMetalHostList_To_v1alpha1_BareMetalHostList(a.(*v1beta1.BareMetalHostList), b.(*BareMetalHostList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BareMetalHostSpec)(nil), (*v1beta1.BareMetalHostSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BareMetalHostSpec_To_v1beta1_BareMetalHostSpec(a.(*BareMetalHostSpec), b.(*v1beta1.BareMetalHostSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.BareMetalHostSpec)(nil), (*BareMetalHostSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_BareMetalHostSpec_To_v1alpha1_BareMetalHostSpec(a.(*v1beta1.BareMetalHostSpec), b.(*BareMetalHostSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BareMetalHostStatus)(nil), (*v1beta1.BareMetalHostStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BareMetalHostStatus_To_v1beta1_BareMetalHostStatus(a.(*BareMetalHostStatus), b.(*v1beta1.BareMetalHostStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.BareMetalHostStatus)(nil), (*BareMetalHostStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_BareMetalHostStatus_To_v1alpha1_BareMetalHostStatus(a.(*v1beta1.BareMetalHostStatus), b.(*BareMetalHostStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CPU)(nil), (*v1beta1.CPU)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CPU_To_v1beta1_CPU(a.(*CPU), b.(*v1beta1.CPU), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.CPU)(nil), (*CPU)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_CPU_To_v1alpha1_CPU(a.(*v1beta1.CPU), b.(*CPU), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CredentialsStatus)(nil), (*v1beta1.CredentialsStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CredentialsStatus_To_v1beta1_CredentialsStatus(a.(*CredentialsStatus), b.(*v1beta1.CredentialsStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.CredentialsStatus)(nil), (*CredentialsStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_CredentialsStatus_To_v1alpha1_CredentialsStatus(a.(*v1beta1.CredentialsStatus), b.(*CredentialsStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CustomDeploy)(nil), (*v1beta1.CustomDeploy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CustomDeploy_To_v1beta1_CustomDeploy(a.(*CustomDeploy), b.(*v1beta1.CustomDeploy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.CustomDeploy)(nil), (*CustomDeploy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_CustomDeploy_To_v1alpha1_CustomDeploy(a.(*v1beta1.CustomDeploy), b.(*CustomDeploy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DetachedAnnotationArguments)(nil), (*v1beta1.DetachedAnnotationArguments)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DetachedAnnotationArguments_To_v1beta1_DetachedAnnotationArguments(a.(*DetachedAnnotationArguments), b.(*v1beta1.DetachedAnnotationArguments), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DetachedAnnotationArguments)(nil), (*DetachedAnnotationArguments)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DetachedAnnotationArguments_To_v1alpha1_DetachedAnnotationArguments(a.(*v1beta1.DetachedAnnotationArguments), b.(*DetachedAnnotationArguments), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Firmware)(nil), (*v1beta1.Firmware)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Firmware_To_v1beta1_Firmware(a.(*Firmware), b.(*v1beta1.Firmware), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Firmware)(nil), (*Firmware)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Firmware_To_v1alpha1_Firmware(a.(*v1beta1.Firmware), b.(*Firmware), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FirmwareConfig)(nil), (*v1beta1.FirmwareConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FirmwareConfig_To_v1beta1_FirmwareConfig(a.(*FirmwareConfig), b.(*v1beta1.FirmwareConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.FirmwareConfig)(nil), (*FirmwareConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FirmwareConfig_To_v1alpha1_FirmwareConfig(a.(*v1beta1.FirmwareConfig), b.(*FirmwareConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HardwareData)(nil), (*v1beta1.HardwareData)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HardwareData_To_v1beta1_HardwareData(a.(*HardwareData), b.(*v1beta1.HardwareData), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.HardwareData)(nil), (*HardwareData)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HardwareData_To_v1alpha1_HardwareData(a.(*v1beta1.HardwareData), b.(*HardwareData), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HardwareDataList)(nil), (*v1beta1.HardwareDataList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HardwareDataList_To_v1beta1_HardwareDataList(a.(*HardwareDataList), b.(*v1beta1.HardwareDataList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.HardwareDataList)(nil), (*HardwareDataList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HardwareDataList_To_v1alpha1_HardwareDataList(a.(*v1beta1.HardwareDataList), b.(*HardwareDataList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HardwareDataSpec)(nil), (*v1beta1.HardwareDataSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HardwareDataSpec_To_v1beta1_HardwareDataSpec(a.(*HardwareDataSpec), b.(*v1beta1.HardwareDataSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.HardwareDataSpec)(nil), (*HardwareDataSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HardwareDataSpec_To_v1alpha1_HardwareDataSpec(a.(*v1beta1.HardwareDataSpec), b.(*HardwareDataSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HardwareDetails)(nil), (*v1beta1.HardwareDetails)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HardwareDetails_To_v1beta1_HardwareDetails(a.(*HardwareDetails), b.(*v1beta1.HardwareDetails), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.HardwareDetails)(nil), (*HardwareDetails)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HardwareDetails_To_v1alpha1_HardwareDetails(a.(*v1beta1.HardwareDetails), b.(*HardwareDetails), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HardwareRAIDVolume)(nil), (*v1beta1.HardwareRAIDVolume)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HardwareRAIDVolume_To_v1beta1_HardwareRAIDVolume(a.(*HardwareRAIDVolume), b.(*v1beta1.HardwareRAIDVolume), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.HardwareRAIDVolume)(nil), (*HardwareRAIDVolume)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HardwareRAIDVolume_To_v1alpha1_HardwareRAIDVolume(a.(*v1beta1.HardwareRAIDVolume), b.(*HardwareRAIDVolume), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HardwareSystemVendor)(nil), (*v1beta1.HardwareSystemVendor)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HardwareSystemVendor_To_v1beta1_HardwareSystemVendor(a.(*HardwareSystemVendor), b.(*v1beta1.HardwareSystemVendor), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.HardwareSystemVendor)(nil), (*HardwareSystemVendor)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HardwareSystemVendor_To_v1alpha1_HardwareSystemVendor(a.(*v1beta1.HardwareSystemVendor), b.(*HardwareSystemVendor), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HostNetworkAttachmentRef)(nil), (*v1beta1.HostNetworkAttachmentRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HostNetworkAttachmentRef_To_v1beta1_HostNetworkAttachmentRef(a.(*HostNetworkAttachmentRef), b.(*v1beta1.HostNetworkAttachmentRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.HostNetworkAttachmentRef)(nil), (*HostNetworkAttachmentRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HostNetworkAttachmentRef_To_v1alpha1_HostNetworkAttachmentRef(a.(*v1beta1.HostNetworkAttachmentRef), b.(*HostNetworkAttachmentRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Image)(nil), (*v1beta1.Image)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Image_To_v1beta1_Image(a.(*Image), b.(*v1beta1.Image), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Image)(nil), (*Image)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Image_To_v1alpha1_Image(a.(*v1beta1.Image), b.(*Image), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LLDP)(nil), (*v1beta1.LLDP)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LLDP_To_v1beta1_LLDP(a.(*LLDP), b.(*v1beta1.LLDP), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.LLDP)(nil), (*LLDP)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_LLDP_To_v1alpha1_LLDP(a.(*v1beta1.LLDP), b.(*LLDP), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NIC)(nil), (*v1beta1.NIC)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NIC_To_v1beta1_NIC(a.(*NIC), b.(*v1beta1.NIC), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.NIC)(nil), (*NIC)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NIC_To_v1alpha1_NIC(a.(*v1beta1.NIC), b.(*NIC), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkInterface)(nil), (*v1beta1.NetworkInterface)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkInterface_To_v1beta1_NetworkInterface(a.(*NetworkInterface), b.(*v1beta1.NetworkInterface), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.NetworkInterface)(nil), (*NetworkInterface)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NetworkInterface_To_v1alpha1_NetworkInterface(a.(*v1beta1.NetworkInterface), b.(*NetworkInterface), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OperationHistory)(nil), (*v1beta1.OperationHistory)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OperationHistory_To_v1beta1_OperationHistory(a.(*OperationHistory), b.(*v1beta1.OperationHistory), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.OperationHistory)(nil), (*OperationHistory)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OperationHistory_To_v1alpha1_OperationHistory(a.(*v1beta1.OperationHistory), b.(*OperationHistory), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OperationMetric)(nil), (*v1beta1.OperationMetric)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OperationMetric_To_v1beta1_OperationMetric(a.(*OperationMetric), b.(*v1beta1.OperationMetric), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.OperationMetric)(nil), (*OperationMetric)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OperationMetric_To_v1alpha1_OperationMetric(a.(*v1beta1.OperationMetric), b.(*OperationMetric), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProvisionStatus)(nil), (*v1beta1.ProvisionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProvisionStatus_To_v1beta1_ProvisionStatus(a.(*ProvisionStatus), b.(*v1beta1.ProvisionStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ProvisionStatus)(nil), (*ProvisionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ProvisionStatus_To_v1alpha1_ProvisionStatus(a.(*v1beta1.ProvisionStatus), b.(*ProvisionStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RAIDConfig)(nil), (*v1beta1.RAIDConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RAIDConfig_To_v1beta1_RAIDConfig(a.(*RAIDConfig), b.(*v1beta1.RAIDConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RAIDConfig)(nil), (*RAIDConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RAIDConfig_To_v1alpha1_RAIDConfig(a.(*v1beta1.RAIDConfig), b.(*RAIDConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RebootAnnotationArguments)(nil), (*v1beta1.RebootAnnotationArguments)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RebootAnnotationArguments_To_v1beta1_RebootAnnotationArguments(a.(*RebootAnnotationArguments), b.(*v1beta1.RebootAnnotationArguments), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RebootAnnotationArguments)(nil), (*RebootAnnotationArguments)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RebootAnnotationArguments_To_v1alpha1_RebootAnnotationArguments(a.(*v1beta1.RebootAnnotationArguments), b.(*RebootAnnotationArguments), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RootDeviceHints)(nil), (*v1beta1.RootDeviceHints)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RootDeviceHints_To_v1beta1_RootDeviceHints(a.(*RootDeviceHints), b.(*v1beta1.RootDeviceHints), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RootDeviceHints)(nil), (*RootDeviceHints)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RootDeviceHints_To_v1alpha1_RootDeviceHints(a.(*v1beta1.RootDeviceHints), b.(*RootDeviceHints), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SoftwareRAIDVolume)(nil), (*v1beta1.SoftwareRAIDVolume)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SoftwareRAIDVolume_To_v1beta1_SoftwareRAIDVolume(a.(*SoftwareRAIDVolume), b.(*v1beta1.SoftwareRAIDVolume), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.SoftwareRAIDVolume)(nil), (*SoftwareRAIDVolume)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SoftwareRAIDVolume_To_v1alpha1_SoftwareRAIDVolume(a.(*v1beta1.SoftwareRAIDVolume), b.(*SoftwareRAIDVolume), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Storage)(nil), (*v1beta1.Storage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Storage_To_v1beta1_Storage(a.(*Storage), b.(*v1beta1.Storage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Storage)(nil), (*Storage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Storage_To_v1alpha1_Storage(a.(*v1beta1.Storage), b.(*Storage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SwitchPortConfig)(nil), (*v1beta1.SwitchPortConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SwitchPortConfig_To_v1beta1_SwitchPortConfig(a.(*SwitchPortConfig), b.(*v1beta1.SwitchPortConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.SwitchPortConfig)(nil), (*SwitchPortConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SwitchPortConfig_To_v1alpha1_SwitchPortConfig(a.(*v1beta1.SwitchPortConfig), b.(*SwitchPortConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SwitchPortIdentifier)(nil), (*v1beta1.SwitchPortIdentifier)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SwitchPortIdentifier_To_v1beta1_SwitchPortIdentifier(a.(*SwitchPortIdentifier), b.(*v1beta1.SwitchPortIdentifier), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.SwitchPortIdentifier)(nil), (*SwitchPortIdentifier)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SwitchPortIdentifier_To_v1alpha1_SwitchPortIdentifier(a.(*v1beta1.SwitchPortIdentifier), b.(*SwitchPortIdentifier), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VLAN)(nil), (*v1beta1.VLAN)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VLAN_To_v1beta1_VLAN(a.(*VLAN), b.(*v1beta1.VLAN), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.VLAN)(nil), (*VLAN)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VLAN_To_v1alpha1_VLAN(a.(*v1beta1.VLAN), b.(*VLAN), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Accelerator_To_v1beta1_Accelerator(in *Accelerator, out *v1beta1.Accelerator, s conversion.Scope) error {
	out.VendorID = in.VendorID
	out.DeviceID = in.DeviceID
	out.Type = in.Type
	out.DeviceInfo = in.DeviceInfo
	out.PCIAddress = in.PCIAddress
	return nil
}

// Convert_v1alpha1_Accelerator_To_v1beta1_Accelerator is an autogenerated conversion function.
func Convert_v1alpha1_Accelerator_To_v1beta1_Accelerator(in *Accelerator, out *v1beta1.Accelerator, s conversion.Scope) error {
	return autoConvert_v1alpha1_Accelerator_To_v1beta1_Accelerator(in, out, s)
}

func autoConvert_v1beta1_Accelerator_To_v1alpha1_Accelerator(in *v1beta1.Accelerator, out *Accelerator, s conversion.Scope) error {
	out.VendorID = in.VendorID
	out.DeviceID = in.DeviceID
	out.Type = in.Type
	out.DeviceInfo = in.DeviceInfo
	out.PCIAddress = in.PCIAddress
	return nil
}

// Convert_v1beta1_Accelerator_To_v1alpha1_Accelerator is an autogenerated conversion function.
func Convert_v1beta1_Accelerator_To_v1alpha1_Accelerator(in *v1beta1.Accelerator, out *Accelerator, s conversion.Scope) error {
	return autoConvert_v1beta1_Accelerator_To_v1alpha1_Accelerator(in, out, s)
}

func autoConvert_v1alpha1_AppliedNetworkAttachmentConfig_To_v1beta1_AppliedNetworkAttachmentConfig(in *AppliedNetworkAttachmentConfig, out *v1beta1.AppliedNetworkAttachmentConfig, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_v1alpha1_SwitchPortConfig_To_v1beta1_SwitchPortConfig(&in.SwitchPortConfig, &out.SwitchPortConfig, s); err != nil {
		return err
	}
	out.SwitchPort = (*v1beta1.SwitchPortIdentifier)(unsafe.Pointer(in.SwitchPort))
	return nil
}

// Convert_v1alpha1_AppliedNetworkAttachmentConfig_To_v1beta1_AppliedNetworkAttachmentConfig is an autogenerated conversion function.
func Convert_v1alpha1_AppliedNetworkAttachmentConfig_To_v1beta1_AppliedNetworkAttachmentConfig(in *AppliedNetworkAttachmentConfig, out *v1beta1.AppliedNetworkAttachmentConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppliedNetworkAttachmentConfig_To_v1beta1_AppliedNetworkAttachmentConfig(in, out, s)
}

func autoConvert_v1beta1_AppliedNetworkAttachmentConfig_To_v1alpha1_AppliedNetworkAttachmentConfig(in *v1beta1.AppliedNetworkAttachmentConfig, out *AppliedNetworkAttachmentConfig, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_v1beta1_SwitchPortConfig_To_v1alpha1_SwitchPortConfig(&in.SwitchPortConfig, &out.SwitchPortConfig, s); err != nil {
		return err
	}
	out.SwitchPort = (*SwitchPortIdentifier)(unsafe.Pointer(in.SwitchPort))
	return nil
}

// Convert_v1beta1_AppliedNetworkAttachmentConfig_To_v1alpha1_AppliedNetworkAttachmentConfig is an autogenerated conversion function.
func Convert_v1beta1_AppliedNetworkAttachmentConfig_To_v1alpha1_AppliedNetworkAttachmentConfig(in *v1beta1.AppliedNetworkAttachmentConfig, out *AppliedNetworkAttachmentConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_AppliedNetworkAttachmentConfig_To_v1alpha1_AppliedNetworkAttachmentConfig(in, out, s)
}

func autoConvert_v1alpha1_BIOS_To_v1beta1_BIOS(in *BIOS, out *v1beta1.BIOS, s conversion.Scope) error {
	out.Date = in.Date
	out.Vendor = in.Vendor
	out.Version = in.Version
	return nil
}

// Convert_v1alpha1_BIOS_To_v1beta1_BIOS is an autogenerated conversion function.
func Convert_v1alpha1_BIOS_To_v1beta1_BIOS(in *BIOS, out *v1beta1.BIOS, s conversion.Scope) error {
	return autoConvert_v1alpha1_BIOS_To_v1beta1_BIOS(in, out, s)
}

func autoConvert_v1beta1_BIOS_To_v1alpha1_BIOS(in *v1beta1.BIOS, out *BIOS, s conversion.Scope) error {
	out.Date = in.Date
	out.Vendor = in.Vendor
	out.Version = in.Version
	return nil
}

// Convert_v1beta1_BIOS_To_v1alpha1_BIOS is an autogenerated conversion function.
func Convert_v1beta1_BIOS_To_v1alpha1_BIOS(in *v1beta1.BIOS, out *BIOS, s conversion.Scope) error {
	return autoConvert_v1beta1_BIOS_To_v1alpha1_BIOS(in, out, s)
}

func autoConvert_v1alpha1_BMCDetails_To_v1beta1_BMCDetails(in *BMCDetails, out *v1beta1.BMCDetails, s conversion.Scope) error {
	out.Address = in.Address
	out.CredentialsName = in.CredentialsName
	out.DisableCertificateVerification = in.DisableCertificateVerification
	return nil
}

// Convert_v1alpha1_BMCDetails_To_v1beta1_BMCDetails is an autogenerated conversion function.
func Convert_v1alpha1_BMCDetails_To_v1beta1_BMCDetails(in *BMCDetails, out *v1beta1.BMCDetails, s conversion.Scope) error {
	return autoConvert_v1alpha1_BMCDetails_To_v1beta1_BMCDetails(in, out, s)
}

func autoConvert_v1beta1_BMCDetails_To_v1alpha1_BMCDetails(in *v1beta1.BMCDetails, out *BMCDetails, s conversion.Scope) error {
	out.Address = in.Address
	out.CredentialsName = in.CredentialsName
	out.DisableCertificateVerification = in.DisableCertificateVerification
	return nil
}

// Convert_v1beta1_BMCDetails_To_v1alpha1_BMCDetails is an autogenerated conversion function.
func Convert_v1beta1_BMCDetails_To_v1alpha1_BMCDetails(in *v1beta1.BMCDetails, out *BMCDetails, s conversion.Scope) error {
	return autoConvert_v1beta1_BMCDetails_To_v1alpha1_BMCDetails(in, out, s)
}

func autoConvert_v1alpha1_BareMetalHost_To_v1beta1_BareMetalHost(in *BareMetalHost, out *v1beta1.BareMetalHost, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_BareMetalHostSpec_To_v1beta1_BareMetalHostSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_BareMetalHostStatus_To_v1beta1_BareMetalHostStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_BareMetalHost_To_v1beta1_BareMetalHost is an autogenerated conversion function.
func Convert_v1alpha1_BareMetalHost_To_v1beta1_BareMetalHost(in *BareMetalHost, out *v1beta1.BareMetalHost, s conversion.Scope) error {
	return autoConvert_v1alpha1_BareMetalHost_To_v1beta1_BareMetalHost(in, out, s)
}

func autoConvert_v1beta1_BareMetalHost_To_v1alpha1_BareMetalHost(in *v1beta1.BareMetalHost, out *BareMetalHost, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_BareMetalHostSpec_To_v1alpha1_BareMetalHostSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_BareMetalHostStatus_To_v1alpha1_BareMetalHostStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_BareMetalHost_To_v1alpha1_BareMetalHost is an autogenerated conversion function.
func Convert_v1beta1_BareMetalHost_To_v1alpha1_BareMetalHost(in *v1beta1.BareMetalHost, out *BareMetalHost, s conversion.Scope) error {
	return autoConvert_v1beta1_BareMetalHost_To_v1alpha1_BareMetalHost(in, out, s)
}

func autoConvert_v1alpha1_BareMetalHostList_To_v1beta1_BareMetalHostList(in *BareMetalHostList, out *v1beta1.BareMetalHostList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.BareMetalHost)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_BareMetalHostList_To_v1beta1_BareMetalHostList is an autogenerated conversion function.
func Convert_v1alpha1_BareMetalHostList_To_v1beta1_BareMetalHostList(in *BareMetalHostList, out *v1beta1.BareMetalHostList, s conversion.Scope) error {
	return autoConvert_v1alpha1_BareMetalHostList_To_v1beta1_BareMetalHostList(in, out, s)
}

func autoConvert_v1beta1_BareMetalHostList_To_v1alpha1_BareMetalHostList(in *v1beta1.BareMetalHostList, out *BareMetalHostList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]BareMetalHost)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_BareMetalHostList_To_v1alpha1_BareMetalHostList is an autogenerated conversion function.
func Convert_v1beta1_BareMetalHostList_To_v1alpha1_BareMetalHostList(in *v1beta1.BareMetalHostList, out *BareMetalHostList, s conversion.Scope) error {
	return autoConvert_v1beta1_BareMetalHostList_To_v1alpha1_BareMetalHostList(in, out, s)
}

func autoConvert_v1alpha1_BareMetalHostSpec_To_v1beta1_BareMetalHostSpec(in *BareMetalHostSpec, out *v1beta1.BareMetalHostSpec, s conversion.Scope) error {
	out.Taints = *(*[]v1.Taint)(unsafe.Pointer(&in.Taints))
	if err := Convert_v1alpha1_BMCDetails_To_v1beta1_BMCDetails(&in.BMC, &out.BMC, s); err != nil {
		return err
	}
	out.RAID = (*v1beta1.RAIDConfig)(unsafe.Pointer(in.RAID))
	out.Firmware = (*v1beta1.FirmwareConfig)(unsafe.Pointer(in.Firmware))
	out.HardwareProfile = in.HardwareProfile
	out.RootDeviceHints = (*v1beta1.RootDeviceHints)(unsafe.Pointer(in.RootDeviceHints))
	out.BootMode = v1beta1.BootMode(in.BootMode)
	out.BootMACAddress = in.BootMACAddress
	out.Online = in.Online
	out.ConsumerRef = (*v1.ObjectReference)(unsafe.Pointer(in.ConsumerRef))
	out.Image = (*v1beta1.Image)(unsafe.Pointer(in.Image))
	out.UserData = (*v1.SecretReference)(unsafe.Pointer(in.UserData))
	out.PreprovisioningNetworkDataName = in.PreprovisioningNetworkDataName
	out.NetworkData = (*v1.SecretReference)(unsafe.Pointer(in.NetworkData))
	out.MetaData = (*v1.SecretReference)(unsafe.Pointer(in.MetaData))
	out.Description = in.Description
	out.ExternallyProvisioned = in.ExternallyProvisioned
	out.AutomatedCleaningMode = v1beta1.AutomatedCleaningMode(in.AutomatedCleaningMode)
	out.CustomDeploy = (*v1beta1.CustomDeploy)(unsafe.Pointer(in.CustomDeploy))
	out.Architecture = in.Architecture
	out.DisablePowerOff = in.DisablePowerOff
	out.InspectionMode = v1beta1.InspectionMode(in.InspectionMode)
	out.NetworkInterfaces = *(*[]v1beta1.NetworkInterface)(unsafe.Pointer(&in.NetworkInterfaces))
	return nil
}

// Convert_v1alpha1_BareMetalHostSpec_To_v1beta1_BareMetalHostSpec is an autogenerated conversion function.
func Convert_v1alpha1_BareMetalHostSpec_To_v1beta1_BareMetalHostSpec(in *BareMetalHostSpec, out *v1beta1.BareMetalHostSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_BareMetalHostSpec_To_v1beta1_BareMetalHostSpec(in, out, s)
}

func autoConvert_v1beta1_BareMetalHostSpec_To_v1alpha1_BareMetalHostSpec(in *v1beta1.BareMetalHostSpec, out *BareMetalHostSpec, s conversion.Scope) error {
	out.Taints = *(*[]v1.Taint)(unsafe.Pointer(&in.Taints))
	if err := Convert_v1beta1_BMCDetails_To_v1alpha1_BMCDetails(&in.BMC, &out.BMC, s); err != nil {
		return err
	}
	out.RAID = (*RAIDConfig)(unsafe.Pointer(in.RAID))
	out.Firmware = (*FirmwareConfig)(unsafe.Pointer(in.Firmware))
	out.HardwareProfile = in.HardwareProfile
	out.RootDeviceHints = (*RootDeviceHints)(unsafe.Pointer(in.RootDeviceHints))
	out.BootMode = BootMode(in.BootMode)
	out.BootMACAddress = in.BootMACAddress
	out.Online = in.Online
	out.ConsumerRef = (*v1.ObjectReference)(unsafe.Pointer(in.ConsumerRef))
	out.Image = (*Image)(unsafe.Pointer(in.Image))
	out.UserData = (*v1.SecretReference)(unsafe.Pointer(in.UserData))
	out.PreprovisioningNetworkDataName = in.PreprovisioningNetworkDataName
	out.NetworkData = (*v1.SecretReference)(unsafe.Pointer(in.NetworkData))
	out.MetaData = (*v1.SecretReference)(unsafe.Pointer(in.MetaData))
	out.Description = in.Description
	out.ExternallyProvisioned = in.ExternallyProvisioned
	out.AutomatedCleaningMode = AutomatedCleaningMode(in.AutomatedCleaningMode)
	out.CustomDeploy = (*CustomDeploy)(unsafe.Pointer(in.CustomDeploy))
	out.Architecture = in.Architecture
	out.DisablePowerOff = in.DisablePowerOff
	out.InspectionMode = InspectionMode(in.InspectionMode)
	out.NetworkInterfaces = *(*[]NetworkInterface)(unsafe.Pointer(&in.NetworkInterfaces))
	return nil
}

// Convert_v1beta1_BareMetalHostSpec_To_v1alpha1_BareMetalHostSpec is an autogenerated conversion function.
func Convert_v1beta1_BareMetalHostSpec_To_v1alpha1_BareMetalHostSpec(in *v1beta1.BareMetalHostSpec, out *BareMetalHostSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_BareMetalHostSpec_To_v1alpha1_BareMetalHostSpec(in, out, s)
}

func autoConvert_v1alpha1_BareMetalHostStatus_To_v1beta1_BareMetalHostStatus(in *BareMetalHostStatus, out *v1beta1.BareMetalHostStatus, s conversion.Scope) error {
	out.OperationalStatus = v1beta1.OperationalStatus(in.OperationalStatus)
	out.ErrorType = v1beta1.ErrorType(in.ErrorType)
	out.LastUpdated = (*metav1.Time)(unsafe.Pointer(in.LastUpdated))
	out.HardwareProfile = in.HardwareProfile
	out.HardwareDetails = (*v1beta1.HardwareDetails)(unsafe.Pointer(in.HardwareDetails))
	if err := Convert_v1alpha1_ProvisionStatus_To_v1beta1_ProvisionStatus(&in.Provisioning, &out.Provisioning, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_CredentialsStatus_To_v1beta1_CredentialsStatus(&in.GoodCredentials, &out.GoodCredentials, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_CredentialsStatus_To_v1beta1_CredentialsStatus(&in.TriedCredentials, &out.TriedCredentials, s); err != nil {
		return err
	}
	out.ErrorMessage = in.ErrorMessage
	out.PoweredOn = in.PoweredOn
	if err := Convert_v1alpha1_OperationHistory_To_v1beta1_OperationHistory(&in.OperationHistory, &out.OperationHistory, s); err != nil {
		return err
	}
	out.ErrorCount = in.ErrorCount
	out.ProvisioningFailCount = in.ProvisioningFailCount
	out.LastAttemptedImage = (*v1beta1.Image)(unsafe.Pointer(in.LastAttemptedImage))
	out.Conditions = *(*[]metav1.Condition)(unsafe.Pointer(&in.Conditions))
	out.AppliedNetworkAttachmentConfigs = *(*[]v1beta1.AppliedNetworkAttachmentConfig)(unsafe.Pointer(&in.AppliedNetworkAttachmentConfigs))
	return nil
}

// Convert_v1alpha1_BareMetalHostStatus_To_v1beta1_BareMetalHostStatus is an autogenerated conversion function.
func Convert_v1alpha1_BareMetalHostStatus_To_v1beta1_BareMetalHostStatus(in *BareMetalHostStatus, out *v1beta1.BareMetalHostStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_BareMetalHostStatus_To_v1beta1_BareMetalHostStatus(in, out, s)
}

func autoConvert_v1beta1_BareMetalHostStatus_To_v1alpha1_BareMetalHostStatus(in *v1beta1.BareMetalHostStatus, out *BareMetalHostStatus, s conversion.Scope) error {
	out.OperationalStatus = OperationalStatus(in.OperationalStatus)
	out.ErrorType = ErrorType(in.ErrorType)
	out.LastUpdated = (*metav1.Time)(unsafe.Pointer(in.LastUpdated))
	out.HardwareProfile = in.HardwareProfile
	out.HardwareDetails = (*HardwareDetails)(unsafe.Pointer(in.HardwareDetails))
	if err := Convert_v1beta1_ProvisionStatus_To_v1alpha1_ProvisionStatus(&in.Provisioning, &out.Provisioning, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_CredentialsStatus_To_v1alpha1_CredentialsStatus(&in.GoodCredentials, &out.GoodCredentials, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_CredentialsStatus_To_v1alpha1_CredentialsStatus(&in.TriedCredentials, &out.TriedCredentials, s); err != nil {
		return err
	}
	out.ErrorMessage = in.ErrorMessage
	out.PoweredOn = in.PoweredOn
	if err := Convert_v1beta1_OperationHistory_To_v1alpha1_OperationHistory(&in.OperationHistory, &out.OperationHistory, s); err != nil {
		return err
	}
	out.ErrorCount = in.ErrorCount
	out.ProvisioningFailCount = in.ProvisioningFailCount
	out.LastAttemptedImage = (*Image)(unsafe.Pointer(in.LastAttemptedImage))
	out.Conditions = *(*[]metav1.Condition)(unsafe.Pointer(&in.Conditions))
	out.AppliedNetworkAttachmentConfigs = *(*[]AppliedNetworkAttachmentConfig)(unsafe.Pointer(&in.AppliedNetworkAttachmentConfigs))
	return nil
}

// Convert_v1beta1_BareMetalHostStatus_To_v1alpha1_BareMetalHostStatus is an autogenerated conversion function.
func Convert_v1beta1_BareMetalHostStatus_To_v1alpha1_BareMetalHostStatus(in *v1beta1.BareMetalHostStatus, out *BareMetalHostStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_BareMetalHostStatus_To_v1alpha1_BareMetalHostStatus(in, out, s)
}

func autoConvert_v1alpha1_CPU_To_v1beta1_CPU(in *CPU, out *v1beta1.CPU, s conversion.Scope) error {
	out.Arch = in.Arch
	out.Model = in.Model
	out.ClockMegahertz = v1beta1.ClockSpeed(in.ClockMegahertz)
	out.Flags = *(*[]string)(unsafe.Pointer(&in.Flags))
	out.Count = in.Count
	return nil
}

// Convert_v1alpha1_CPU_To_v1beta1_CPU is an autogenerated conversion function.
func Convert_v1alpha1_CPU_To_v1beta1_CPU(in *CPU, out *v1beta1.CPU, s conversion.Scope) error {
	return autoConvert_v1alpha1_CPU_To_v1beta1_CPU(in, out, s)
}

func autoConvert_v1beta1_CPU_To_v1alpha1_CPU(in *v1beta1.CPU, out *CPU, s conversion.Scope) error {
	out.Arch = in.Arch
	out.Model = in.Model
	out.ClockMegahertz = ClockSpeed(in.ClockMegahertz)
	out.Flags = *(*[]string)(unsafe.Pointer(&in.Flags))
	out.Count = in.Count
	return nil
}

// Convert_v1beta1_CPU_To_v1alpha1_CPU is an autogenerated conversion function.
func Convert_v1beta1_CPU_To_v1alpha1_CPU(in *v1beta1.CPU, out *CPU, s conversion.Scope) error {
	return autoConvert_v1beta1_CPU_To_v1alpha1_CPU(in, out, s)
}

func autoConvert_v1alpha1_CredentialsStatus_To_v1beta1_CredentialsStatus(in *CredentialsStatus, out *v1beta1.CredentialsStatus, s conversion.Scope) error {
	out.Reference = (*v1.SecretReference)(unsafe.Pointer(in.Reference))
	out.Version = in.Version
	return nil
}

// Convert_v1alpha1_CredentialsStatus_To_v1beta1_CredentialsStatus is an autogenerated conversion function.
func Convert_v1alpha1_CredentialsStatus_To_v1beta1_CredentialsStatus(in *CredentialsStatus, out *v1beta1.CredentialsStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_CredentialsStatus_To_v1beta1_CredentialsStatus(in, out, s)
}

func autoConvert_v1beta1_CredentialsStatus_To_v1alpha1_CredentialsStatus(in *v1beta1.CredentialsStatus, out *CredentialsStatus, s conversion.Scope) error {
	out.Reference = (*v1.SecretReference)(unsafe.Pointer(in.Reference))
	out.Version = in.Version
	return nil
}

// Convert_v1beta1_CredentialsStatus_To_v1alpha1_CredentialsStatus is an autogenerated conversion function.
func Convert_v1beta1_CredentialsStatus_To_v1alpha1_CredentialsStatus(in *v1beta1.CredentialsStatus, out *CredentialsStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_CredentialsStatus_To_v1alpha1_CredentialsStatus(in, out, s)
}

func autoConvert_v1alpha1_CustomDeploy_To_v1beta1_CustomDeploy(in *CustomDeploy, out *v1beta1.CustomDeploy, s conversion.Scope) error {
	out.Method = in.Method
	return nil
}

// Convert_v1alpha1_CustomDeploy_To_v1beta1_CustomDeploy is an autogenerated conversion function.
func Convert_v1alpha1_CustomDeploy_To_v1beta1_CustomDeploy(in *CustomDeploy, out *v1beta1.CustomDeploy, s conversion.Scope) error {
	return autoConvert_v1alpha1_CustomDeploy_To_v1beta1_CustomDeploy(in, out, s)
}

func autoConvert_v1beta1_CustomDeploy_To_v1alpha1_CustomDeploy(in *v1beta1.CustomDeploy, out *CustomDeploy, s conversion.Scope) error {
	out.Method = in.Method
	return nil
}

// Convert_v1beta1_CustomDeploy_To_v1alpha1_CustomDeploy is an autogenerated conversion function.
func Convert_v1beta1_CustomDeploy_To_v1alpha1_CustomDeploy(in *v1beta1.CustomDeploy, out *CustomDeploy, s conversion.Scope) error {
	return autoConvert_v1beta1_CustomDeploy_To_v1alpha1_CustomDeploy(in, out, s)
}

func autoConvert_v1alpha1_DetachedAnnotationArguments_To_v1beta1_DetachedAnnotationArguments(in *DetachedAnnotationArguments, out *v1beta1.DetachedAnnotationArguments, s conversion.Scope) error {
	out.DeleteAction = v1beta1.DetachedDeleteAction(in.DeleteAction)
	out.Force = in.Force
	return nil
}

// Convert_v1alpha1_DetachedAnnotationArguments_To_v1beta1_DetachedAnnotationArguments is an autogenerated conversion function.
func Convert_v1alpha1_DetachedAnnotationArguments_To_v1beta1_DetachedAnnotationArguments(in *DetachedAnnotationArguments, out *v1beta1.DetachedAnnotationArguments, s conversion.Scope) error {
	return autoConvert_v1alpha1_DetachedAnnotationArguments_To_v1beta1_DetachedAnnotationArguments(in, out, s)
}

func autoConvert_v1beta1_DetachedAnnotationArguments_To_v1alpha1_DetachedAnnotationArguments(in *v1beta1.DetachedAnnotationArguments, out *DetachedAnnotationArguments, s conversion.Scope) error {
	out.DeleteAction = DetachedDeleteAction(in.DeleteAction)
	out.Force = in.Force
	return nil
}

// Convert_v1beta1_DetachedAnnotationArguments_To_v1alpha1_DetachedAnnotationArguments is an autogenerated conversion function.
func Convert_v1beta1_DetachedAnnotationArguments_To_v1alpha1_DetachedAnnotationArguments(in *v1beta1.DetachedAnnotationArguments, out *DetachedAnnotationArguments, s conversion.Scope) error {
	return autoConvert_v1beta1_DetachedAnnotationArguments_To_v1alpha1_DetachedAnnotationArguments(in, out, s)
}

func autoConvert_v1alpha1_Firmware_To_v1beta1_Firmware(in *Firmware, out *v1beta1.Firmware, s conversion.Scope) error {
	if err := Convert_v1alpha1_BIOS_To_v1beta1_BIOS(&in.BIOS, &out.BIOS, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Firmware_To_v1beta1_Firmware is an autogenerated conversion function.
func Convert_v1alpha1_Firmware_To_v1beta1_Firmware(in *Firmware, out *v1beta1.Firmware, s conversion.Scope) error {
	return autoConvert_v1alpha1_Firmware_To_v1beta1_Firmware(in, out, s)
}

func autoConvert_v1beta1_Firmware_To_v1alpha1_Firmware(in *v1beta1.Firmware, out *Firmware, s conversion.Scope) error {
	if err := Convert_v1beta1_BIOS_To_v1alpha1_BIOS(&in.BIOS, &out.BIOS, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Firmware_To_v1alpha1_Firmware is an autogenerated conversion function.
func Convert_v1beta1_Firmware_To_v1alpha1_Firmware(in *v1beta1.Firmware, out *Firmware, s conversion.Scope) error {
	return autoConvert_v1beta1_Firmware_To_v1alpha1_Firmware(in, out, s)
}

func autoConvert_v1alpha1_FirmwareConfig_To_v1beta1_FirmwareConfig(in *FirmwareConfig, out *v1beta1.FirmwareConfig, s conversion.Scope) error {
	out.VirtualizationEnabled = (*bool)(unsafe.Pointer(in.VirtualizationEnabled))
	out.SimultaneousMultithreadingEnabled = (*bool)(unsafe.Pointer(in.SimultaneousMultithreadingEnabled))
	out.SriovEnabled = (*bool)(unsafe.Pointer(in.SriovEnabled))
	return nil
}

// Convert_v1alpha1_FirmwareConfig_To_v1beta1_FirmwareConfig is an autogenerated conversion function.
func Convert_v1alpha1_FirmwareConfig_To_v1beta1_FirmwareConfig(in *FirmwareConfig, out *v1beta1.FirmwareConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_FirmwareConfig_To_v1beta1_FirmwareConfig(in, out, s)
}

func autoConvert_v1beta1_FirmwareConfig_To_v1alpha1_FirmwareConfig(in *v1beta1.FirmwareConfig, out *FirmwareConfig, s conversion.Scope) error {
	out.VirtualizationEnabled = (*bool)(unsafe.Pointer(in.VirtualizationEnabled))
	out.SimultaneousMultithreadingEnabled = (*bool)(unsafe.Pointer(in.SimultaneousMultithreadingEnabled))
	out.SriovEnabled = (*bool)(unsafe.Pointer(in.SriovEnabled))
	return nil
}

// Convert_v1beta1_FirmwareConfig_To_v1alpha1_FirmwareConfig is an autogenerated conversion function.
func Convert_v1beta1_FirmwareConfig_To_v1alpha1_FirmwareConfig(in *v1beta1.FirmwareConfig, out *FirmwareConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_FirmwareConfig_To_v1alpha1_FirmwareConfig(in, out, s)
}

func autoConvert_v1alpha1_HardwareData_To_v1beta1_HardwareData(in *HardwareData, out *v1beta1.HardwareData, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_HardwareDataSpec_To_v1beta1_HardwareDataSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_HardwareData_To_v1beta1_HardwareData is an autogenerated conversion function.
func Convert_v1alpha1_HardwareData_To_v1beta1_HardwareData(in *HardwareData, out *v1beta1.HardwareData, s conversion.Scope) error {
	return autoConvert_v1alpha1_HardwareData_To_v1beta1_HardwareData(in, out, s)
}

func autoConvert_v1beta1_HardwareData_To_v1alpha1_HardwareData(in *v1beta1.HardwareData, out *HardwareData, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_HardwareDataSpec_To_v1alpha1_HardwareDataSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_HardwareData_To_v1alpha1_HardwareData is an autogenerated conversion function.
func Convert_v1beta1_HardwareData_To_v1alpha1_HardwareData(in *v1beta1.HardwareData, out *HardwareData, s conversion.Scope) error {
	return autoConvert_v1beta1_HardwareData_To_v1alpha1_HardwareData(in, out, s)
}

func autoConvert_v1alpha1_HardwareDataList_To_v1beta1_HardwareDataList(in *HardwareDataList, out *v1beta1.HardwareDataList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.HardwareData)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_HardwareDataList_To_v1beta1_HardwareDataList is an autogenerated conversion function.
func Convert_v1alpha1_HardwareDataList_To_v1beta1_HardwareDataList(in *HardwareDataList, out *v1beta1.HardwareDataList, s conversion.Scope) error {
	return autoConvert_v1alpha1_HardwareDataList_To_v1beta1_HardwareDataList(in, out, s)
}

func autoConvert_v1beta1_HardwareDataList_To_v1alpha1_HardwareDataList(in *v1beta1.HardwareDataList, out *HardwareDataList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]HardwareData)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_HardwareDataList_To_v1alpha1_HardwareDataList is an autogenerated conversion function.
func Convert_v1beta1_HardwareDataList_To_v1alpha1_HardwareDataList(in *v1beta1.HardwareDataList, out *HardwareDataList, s conversion.Scope) error {
	return autoConvert_v1beta1_HardwareDataList_To_v1alpha1_HardwareDataList(in, out, s)
}

func autoConvert_v1alpha1_HardwareDataSpec_To_v1beta1_HardwareDataSpec(in *HardwareDataSpec, out *v1beta1.HardwareDataSpec, s conversion.Scope) error {
	out.HardwareDetails = (*v1beta1.HardwareDetails)(unsafe.Pointer(in.HardwareDetails))
	return nil
}

// Convert_v1alpha1_HardwareDataSpec_To_v1beta1_HardwareDataSpec is an autogenerated conversion function.
func Convert_v1alpha1_HardwareDataSpec_To_v1beta1_HardwareDataSpec(in *HardwareDataSpec, out *v1beta1.HardwareDataSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_HardwareDataSpec_To_v1beta1_HardwareDataSpec(in, out, s)
}

func autoConvert_v1beta1_HardwareDataSpec_To_v1alpha1_HardwareDataSpec(in *v1beta1.HardwareDataSpec, out *HardwareDataSpec, s conversion.Scope) error {
	out.HardwareDetails = (*HardwareDetails)(unsafe.Pointer(in.HardwareDetails))
	return nil
}

// Convert_v1beta1_HardwareDataSpec_To_v1alpha1_HardwareDataSpec is an autogenerated conversion function.
func Convert_v1beta1_HardwareDataSpec_To_v1alpha1_HardwareDataSpec(in *v1beta1.HardwareDataSpec, out *HardwareDataSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_HardwareDataSpec_To_v1alpha1_HardwareDataSpec(in, out, s)
}

func autoConvert_v1alpha1_HardwareDetails_To_v1beta1_HardwareDetails(in *HardwareDetails, out *v1beta1.HardwareDetails, s conversion.Scope) error {
	out.Accelerators = *(*[]v1beta1.Accelerator)(unsafe.Pointer(&in.Accelerators))
	if err := Convert_v1alpha1_HardwareSystemVendor_To_v1beta1_HardwareSystemVendor(&in.SystemVendor, &out.SystemVendor, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_Firmware_To_v1beta1_Firmware(&in.Firmware, &out.Firmware, s); err != nil {
		return err
	}
	out.RAMMebibytes = in.RAMMebibytes
	out.NIC = *(*[]v1beta1.NIC)(unsafe.Pointer(&in.NIC))
	out.Storage = *(*[]v1beta1.Storage)(unsafe.Pointer(&in.Storage))
	if err := Convert_v1alpha1_CPU_To_v1beta1_CPU(&in.CPU, &out.CPU, s); err != nil {
		return err
	}
	out.Hostname = in.Hostname
	return nil
}

// Convert_v1alpha1_HardwareDetails_To_v1beta1_HardwareDetails is an autogenerated conversion function.
func Convert_v1alpha1_HardwareDetails_To_v1beta1_HardwareDetails(in *HardwareDetails, out *v1beta1.HardwareDetails, s conversion.Scope) error {
	return autoConvert_v1alpha1_HardwareDetails_To_v1beta1_HardwareDetails(in, out, s)
}

func autoConvert_v1beta1_HardwareDetails_To_v1alpha1_HardwareDetails(in *v1beta1.HardwareDetails, out *HardwareDetails, s conversion.Scope) error {
	out.Accelerators = *(*[]Accelerator)(unsafe.Pointer(&in.Accelerators))
	if err := Convert_v1beta1_HardwareSystemVendor_To_v1alpha1_HardwareSystemVendor(&in.SystemVendor, &out.SystemVendor, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_Firmware_To_v1alpha1_Firmware(&in.Firmware, &out.Firmware, s); err != nil {
		return err
	}
	out.RAMMebibytes = in.RAMMebibytes
	out.NIC = *(*[]NIC)(unsafe.Pointer(&in.NIC))
	out.Storage = *(*[]Storage)(unsafe.Pointer(&in.Storage))
	if err := Convert_v1beta1_CPU_To_v1alpha1_CPU(&in.CPU, &out.CPU, s); err != nil {
		return err
	}
	out.Hostname = in.Hostname
	return nil
}

// Convert_v1beta1_HardwareDetails_To_v1alpha1_HardwareDetails is an autogenerated conversion function.
func Convert_v1beta1_HardwareDetails_To_v1alpha1_HardwareDetails(in *v1beta1.HardwareDetails, out *HardwareDetails, s conversion.Scope) error {
	return autoConvert_v1beta1_HardwareDetails_To_v1alpha1_HardwareDetails(in, out, s)
}

func autoConvert_v1alpha1_HardwareRAIDVolume_To_v1beta1_HardwareRAIDVolume(in *HardwareRAIDVolume, out *v1beta1.HardwareRAIDVolume, s conversion.Scope) error {
	out.SizeGibibytes = (*int)(unsafe.Pointer(in.SizeGibibytes))
	out.Level = in.Level
	out.Name = in.Name
	out.Rotational = (*bool)(unsafe.Pointer(in.Rotational))
	out.NumberOfPhysicalDisks = (*int)(unsafe.Pointer(in.NumberOfPhysicalDisks))
	out.Controller = in.Controller
	out.PhysicalDisks = *(*[]string)(unsafe.Pointer(&in.PhysicalDisks))
	return nil
}

// Convert_v1alpha1_HardwareRAIDVolume_To_v1beta1_HardwareRAIDVolume is an autogenerated conversion function.
func Convert_v1alpha1_HardwareRAIDVolume_To_v1beta1_HardwareRAIDVolume(in *HardwareRAIDVolume, out *v1beta1.HardwareRAIDVolume, s conversion.Scope) error {
	return autoConvert_v1alpha1_HardwareRAIDVolume_To_v1beta1_HardwareRAIDVolume(in, out, s)
}

func autoConvert_v1beta1_HardwareRAIDVolume_To_v1alpha1_HardwareRAIDVolume(in *v1beta1.HardwareRAIDVolume, out *HardwareRAIDVolume, s conversion.Scope) error {
	out.SizeGibibytes = (*int)(unsafe.Pointer(in.SizeGibibytes))
	out.Level = in.Level
	out.Name = in.Name
	out.Rotational = (*bool)(unsafe.Pointer(in.Rotational))
	out.NumberOfPhysicalDisks = (*int)(unsafe.Pointer(in.NumberOfPhysicalDisks))
	out.Controller = in.Controller
	out.PhysicalDisks = *(*[]string)(unsafe.Pointer(&in.PhysicalDisks))
	return nil
}

// Convert_v1beta1_HardwareRAIDVolume_To_v1alpha1_HardwareRAIDVolume is an autogenerated conversion function.
func Convert_v1beta1_HardwareRAIDVolume_To_v1alpha1_HardwareRAIDVolume(in *v1beta1.HardwareRAIDVolume, out *HardwareRAIDVolume, s conversion.Scope) error {
	return autoConvert_v1beta1_HardwareRAIDVolume_To_v1alpha1_HardwareRAIDVolume(in, out, s)
}

func autoConvert_v1alpha1_HardwareSystemVendor_To_v1beta1_HardwareSystemVendor(in *HardwareSystemVendor, out *v1beta1.HardwareSystemVendor, s conversion.Scope) error {
	out.Manufacturer = in.Manufacturer
	out.ProductName = in.ProductName
	out.SerialNumber = in.SerialNumber
	return nil
}

// Convert_v1alpha1_HardwareSystemVendor_To_v1beta1_HardwareSystemVendor is an autogenerated conversion function.
func Convert_v1alpha1_HardwareSystemVendor_To_v1beta1_HardwareSystemVendor(in *HardwareSystemVendor, out *v1beta1.HardwareSystemVendor, s conversion.Scope) error {
	return autoConvert_v1alpha1_HardwareSystemVendor_To_v1beta1_HardwareSystemVendor(in, out, s)
}

func autoConvert_v1beta1_HardwareSystemVendor_To_v1alpha1_HardwareSystemVendor(in *v1beta1.HardwareSystemVendor, out *HardwareSystemVendor, s conversion.Scope) error {
	out.Manufacturer = in.Manufacturer
	out.ProductName = in.ProductName
	out.SerialNumber = in.SerialNumber
	return nil
}

// Convert_v1beta1_HardwareSystemVendor_To_v1alpha1_HardwareSystemVendor is an autogenerated conversion function.
func Convert_v1beta1_HardwareSystemVendor_To_v1alpha1_HardwareSystemVendor(in *v1beta1.HardwareSystemVendor, out *HardwareSystemVendor, s conversion.Scope) error {
	return autoConvert_v1beta1_HardwareSystemVendor_To_v1alpha1_HardwareSystemVendor(in, out, s)
}

func autoConvert_v1alpha1_HostNetworkAttachmentRef_To_v1beta1_HostNetworkAttachmentRef(in *HostNetworkAttachmentRef, out *v1beta1.HostNetworkAttachmentRef, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_v1alpha1_HostNetworkAttachmentRef_To_v1beta1_HostNetworkAttachmentRef is an autogenerated conversion function.
func Convert_v1alpha1_HostNetworkAttachmentRef_To_v1beta1_HostNetworkAttachmentRef(in *HostNetworkAttachmentRef, out *v1beta1.HostNetworkAttachmentRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_HostNetworkAttachmentRef_To_v1beta1_HostNetworkAttachmentRef(in, out, s)
}

func autoConvert_v1beta1_HostNetworkAttachmentRef_To_v1alpha1_HostNetworkAttachmentRef(in *v1beta1.HostNetworkAttachmentRef, out *HostNetworkAttachmentRef, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_v1beta1_HostNetworkAttachmentRef_To_v1alpha1_HostNetworkAttachmentRef is an autogenerated conversion function.
func Convert_v1beta1_HostNetworkAttachmentRef_To_v1alpha1_HostNetworkAttachmentRef(in *v1beta1.HostNetworkAttachmentRef, out *HostNetworkAttachmentRef, s conversion.Scope) error {
	return autoConvert_v1beta1_HostNetworkAttachmentRef_To_v1alpha1_HostNetworkAttachmentRef(in, out, s)
}

func autoConvert_v1alpha1_Image_To_v1beta1_Image(in *Image, out *v1beta1.Image, s conversion.Scope) error {
	out.URL = in.URL
	out.Checksum = in.Checksum
	out.ChecksumType = v1beta1.ChecksumType(in.ChecksumType)
	out.DiskFormat = (*string)(unsafe.Pointer(in.DiskFormat))
	out.OCIAuthSecretName = (*string)(unsafe.Pointer(in.OCIAuthSecretName))
	return nil
}

// Convert_v1alpha1_Image_To_v1beta1_Image is an autogenerated conversion function.
func Convert_v1alpha1_Image_To_v1beta1_Image(in *Image, out *v1beta1.Image, s conversion.Scope) error {
	return autoConvert_v1alpha1_Image_To_v1beta1_Image(in, out, s)
}

func autoConvert_v1beta1_Image_To_v1alpha1_Image(in *v1beta1.Image, out *Image, s conversion.Scope) error {
	out.URL = in.URL
	out.Checksum = in.Checksum
	out.ChecksumType = ChecksumType(in.ChecksumType)
	out.DiskFormat = (*string)(unsafe.Pointer(in.DiskFormat))
	out.OCIAuthSecretName = (*string)(unsafe.Pointer(in.OCIAuthSecretName))
	return nil
}

// Convert_v1beta1_Image_To_v1alpha1_Image is an autogenerated conversion function.
func Convert_v1beta1_Image_To_v1alpha1_Image(in *v1beta1.Image, out *Image, s conversion.Scope) error {
	return autoConvert_v1beta1_Image_To_v1alpha1_Image(in, out, s)
}

func autoConvert_v1alpha1_LLDP_To_v1beta1_LLDP(in *LLDP, out *v1beta1.LLDP, s conversion.Scope) error {
	out.SwitchID = in.SwitchID
	out.PortID = in.PortID
	out.SwitchSystemName = in.SwitchSystemName
	return nil
}

// Convert_v1alpha1_LLDP_To_v1beta1_LLDP is an autogenerated conversion function.
func Convert_v1alpha1_LLDP_To_v1beta1_LLDP(in *LLDP, out *v1beta1.LLDP, s conversion.Scope) error {
	return autoConvert_v1alpha1_LLDP_To_v1beta1_LLDP(in, out, s)
}

func autoConvert_v1beta1_LLDP_To_v1alpha1_LLDP(in *v1beta1.LLDP, out *LLDP, s conversion.Scope) error {
	out.SwitchID = in.SwitchID
	out.PortID = in.PortID
	out.SwitchSystemName = in.SwitchSystemName
	return nil
}

// Convert_v1beta1_LLDP_To_v1alpha1_LLDP is an autogenerated conversion function.
func Convert_v1beta1_LLDP_To_v1alpha1_LLDP(in *v1beta1.LLDP, out *LLDP, s conversion.Scope) error {
	return autoConvert_v1beta1_LLDP_To_v1alpha1_LLDP(in, out, s)
}

func autoConvert_v1alpha1_NIC_To_v1beta1_NIC(in *NIC, out *v1beta1.NIC, s conversion.Scope) error {
	out.Name = in.Name
	out.Model = in.Model
	out.MAC = in.MAC
	out.IP = in.IP
	out.SpeedGbps = in.SpeedGbps
	out.VLANs = *(*[]v1beta1.VLAN)(unsafe.Pointer(&in.VLANs))
	out.VLANID = v1beta1.VLANID(in.VLANID)
	out.PXE = in.PXE
	out.LLDP = (*v1beta1.LLDP)(unsafe.Pointer(in.LLDP))
	out.PCIAddress = in.PCIAddress
	return nil
}

// Convert_v1alpha1_NIC_To_v1beta1_NIC is an autogenerated conversion function.
func Convert_v1alpha1_NIC_To_v1beta1_NIC(in *NIC, out *v1beta1.NIC, s conversion.Scope) error {
	return autoConvert_v1alpha1_NIC_To_v1beta1_NIC(in, out, s)
}

func autoConvert_v1beta1_NIC_To_v1alpha1_NIC(in *v1beta1.NIC, out *NIC, s conversion.Scope) error {
	out.Name = in.Name
	out.Model = in.Model
	out.MAC = in.MAC
	out.IP = in.IP
	out.SpeedGbps = in.SpeedGbps
	out.VLANs = *(*[]VLAN)(unsafe.Pointer(&in.VLANs))
	out.VLANID = VLANID(in.VLANID)
	out.PXE = in.PXE
	out.LLDP = (*LLDP)(unsafe.Pointer(in.LLDP))
	out.PCIAddress = in.PCIAddress
	return nil
}

// Convert_v1beta1_NIC_To_v1alpha1_NIC is an autogenerated conversion function.
func Convert_v1beta1_NIC_To_v1alpha1_NIC(in *v1beta1.NIC, out *NIC, s conversion.Scope) error {
	return autoConvert_v1beta1_NIC_To_v1alpha1_NIC(in, out, s)
}

func autoConvert_v1alpha1_NetworkInterface_To_v1beta1_NetworkInterface(in *NetworkInterface, out *v1beta1.NetworkInterface, s conversion.Scope) error {
	out.Name = in.Name
	out.MACAddress = in.MACAddress
	if err := Convert_v1alpha1_HostNetworkAttachmentRef_To_v1beta1_HostNetworkAttachmentRef(&in.HostNetworkAttachment, &out.HostNetworkAttachment, s); err != nil {
		return err
	}
	out.SwitchPort = (*v1beta1.SwitchPortIdentifier)(unsafe.Pointer(in.SwitchPort))
	return nil
}

// Convert_v1alpha1_NetworkInterface_To_v1beta1_NetworkInterface is an autogenerated conversion function.
func Convert_v1alpha1_NetworkInterface_To_v1beta1_NetworkInterface(in *NetworkInterface, out *v1beta1.NetworkInterface, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkInterface_To_v1beta1_NetworkInterface(in, out, s)
}

func autoConvert_v1beta1_NetworkInterface_To_v1alpha1_NetworkInterface(in *v1beta1.NetworkInterface, out *NetworkInterface, s conversion.Scope) error {
	out.Name = in.Name
	out.MACAddress = in.MACAddress
	if err := Convert_v1beta1_HostNetworkAttachmentRef_To_v1alpha1_HostNetworkAttachmentRef(&in.HostNetworkAttachment, &out.HostNetworkAttachment, s); err != nil {
		return err
	}
	out.SwitchPort = (*SwitchPortIdentifier)(unsafe.Pointer(in.SwitchPort))
	return nil
}

// Convert_v1beta1_NetworkInterface_To_v1alpha1_NetworkInterface is an autogenerated conversion function.
func Convert_v1beta1_NetworkInterface_To_v1alpha1_NetworkInterface(in *v1beta1.NetworkInterface, out *NetworkInterface, s conversion.Scope) error {
	return autoConvert_v1beta1_NetworkInterface_To_v1alpha1_NetworkInterface(in, out, s)
}

func autoConvert_v1alpha1_OperationHistory_To_v1beta1_OperationHistory(in *OperationHistory, out *v1beta1.OperationHistory, s conversion.Scope) error {
	if err := Convert_v1alpha1_OperationMetric_To_v1beta1_OperationMetric(&in.Register, &out.Register, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_OperationMetric_To_v1beta1_OperationMetric(&in.Inspect, &out.Inspect, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_OperationMetric_To_v1beta1_OperationMetric(&in.Provision, &out.Provision, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_OperationMetric_To_v1beta1_OperationMetric(&in.Deprovision, &out.Deprovision, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_OperationHistory_To_v1beta1_OperationHistory is an autogenerated conversion function.
func Convert_v1alpha1_OperationHistory_To_v1beta1_OperationHistory(in *OperationHistory, out *v1beta1.OperationHistory, s conversion.Scope) error {
	return autoConvert_v1alpha1_OperationHistory_To_v1beta1_OperationHistory(in, out, s)
}

func autoConvert_v1beta1_OperationHistory_To_v1alpha1_OperationHistory(in *v1beta1.OperationHistory, out *OperationHistory, s conversion.Scope) error {
	if err := Convert_v1beta1_OperationMetric_To_v1alpha1_OperationMetric(&in.Register, &out.Register, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OperationMetric_To_v1alpha1_OperationMetric(&in.Inspect, &out.Inspect, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OperationMetric_To_v1alpha1_OperationMetric(&in.Provision, &out.Provision, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OperationMetric_To_v1alpha1_OperationMetric(&in.Deprovision, &out.Deprovision, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_OperationHistory_To_v1alpha1_OperationHistory is an autogenerated conversion function.
func Convert_v1beta1_OperationHistory_To_v1alpha1_OperationHistory(in *v1beta1.OperationHistory, out *OperationHistory, s conversion.Scope) error {
	return autoConvert_v1beta1_OperationHistory_To_v1alpha1_OperationHistory(in, out, s)
}

func autoConvert_v1alpha1_OperationMetric_To_v1beta1_OperationMetric(in *OperationMetric, out *v1beta1.OperationMetric, s conversion.Scope) error {
	out.Start = in.Start
	out.End = in.End
	return nil
}

// Convert_v1alpha1_OperationMetric_To_v1beta1_OperationMetric is an autogenerated conversion function.
func Convert_v1alpha1_OperationMetric_To_v1beta1_OperationMetric(in *OperationMetric, out *v1beta1.OperationMetric, s conversion.Scope) error {
	return autoConvert_v1alpha1_OperationMetric_To_v1beta1_OperationMetric(in, out, s)
}

func autoConvert_v1beta1_OperationMetric_To_v1alpha1_OperationMetric(in *v1beta1.OperationMetric, out *OperationMetric, s conversion.Scope) error {
	out.Start = in.Start
	out.End = in.End
	return nil
}

// Convert_v1beta1_OperationMetric_To_v1alpha1_OperationMetric is an autogenerated conversion function.
func Convert_v1beta1_OperationMetric_To_v1alpha1_OperationMetric(in *v1beta1.OperationMetric, out *OperationMetric, s conversion.Scope) error {
	return autoConvert_v1beta1_OperationMetric_To_v1alpha1_OperationMetric(in, out, s)
}

func autoConvert_v1alpha1_ProvisionStatus_To_v1beta1_ProvisionStatus(in *ProvisionStatus, out *v1beta1.ProvisionStatus, s conversion.Scope) error {
	out.State = v1beta1.ProvisioningState(in.State)
	out.ID = in.ID
	if err := Convert_v1alpha1_Image_To_v1beta1_Image(&in.Image, &out.Image, s); err != nil {
		return err
	}
	out.RootDeviceHints = (*v1beta1.RootDeviceHints)(unsafe.Pointer(in.RootDeviceHints))
	out.BootMode = v1beta1.BootMode(in.BootMode)
	out.RAID = (*v1beta1.RAIDConfig)(unsafe.Pointer(in.RAID))
	out.Firmware = (*v1beta1.FirmwareConfig)(unsafe.Pointer(in.Firmware))
	out.CustomDeploy = (*v1beta1.CustomDeploy)(unsafe.Pointer(in.CustomDeploy))
	return nil
}

// Convert_v1alpha1_ProvisionStatus_To_v1beta1_ProvisionStatus is an autogenerated conversion function.
func Convert_v1alpha1_ProvisionStatus_To_v1beta1_ProvisionStatus(in *ProvisionStatus, out *v1beta1.ProvisionStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProvisionStatus_To_v1beta1_ProvisionStatus(in, out, s)
}

func autoConvert_v1beta1_ProvisionStatus_To_v1alpha1_ProvisionStatus(in *v1beta1.ProvisionStatus, out *ProvisionStatus, s conversion.Scope) error {
	out.State = ProvisioningState(in.State)
	out.ID = in.ID
	if err := Convert_v1beta1_Image_To_v1alpha1_Image(&in.Image, &out.Image, s); err != nil {
		return err
	}
	out.RootDeviceHints = (*RootDeviceHints)(unsafe.Pointer(in.RootDeviceHints))
	out.BootMode = BootMode(in.BootMode)
	out.RAID = (*RAIDConfig)(unsafe.Pointer(in.RAID))
	out.Firmware = (*FirmwareConfig)(unsafe.Pointer(in.Firmware))
	out.CustomDeploy = (*CustomDeploy)(unsafe.Pointer(in.CustomDeploy))
	return nil
}

// Convert_v1beta1_ProvisionStatus_To_v1alpha1_ProvisionStatus is an autogenerated conversion function.
func Convert_v1beta1_ProvisionStatus_To_v1alpha1_ProvisionStatus(in *v1beta1.ProvisionStatus, out *ProvisionStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_ProvisionStatus_To_v1alpha1_ProvisionStatus(in, out, s)
}

func autoConvert_v1alpha1_RAIDConfig_To_v1beta1_RAIDConfig(in *RAIDConfig, out *v1beta1.RAIDConfig, s conversion.Scope) error {
	out.HardwareRAIDVolumes = *(*[]v1beta1.HardwareRAIDVolume)(unsafe.Pointer(&in.HardwareRAIDVolumes))
	out.SoftwareRAIDVolumes = *(*[]v1beta1.SoftwareRAIDVolume)(unsafe.Pointer(&in.SoftwareRAIDVolumes))
	return nil
}

// Convert_v1alpha1_RAIDConfig_To_v1beta1_RAIDConfig is an autogenerated conversion function.
func Convert_v1alpha1_RAIDConfig_To_v1beta1_RAIDConfig(in *RAIDConfig, out *v1beta1.RAIDConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_RAIDConfig_To_v1beta1_RAIDConfig(in, out, s)
}

func autoConvert_v1beta1_RAIDConfig_To_v1alpha1_RAIDConfig(in *v1beta1.RAIDConfig, out *RAIDConfig, s conversion.Scope) error {
	out.HardwareRAIDVolumes = *(*[]HardwareRAIDVolume)(unsafe.Pointer(&in.HardwareRAIDVolumes))
	out.SoftwareRAIDVolumes = *(*[]SoftwareRAIDVolume)(unsafe.Pointer(&in.SoftwareRAIDVolumes))
	return nil
}

// Convert_v1beta1_RAIDConfig_To_v1alpha1_RAIDConfig is an autogenerated conversion function.
func Convert_v1beta1_RAIDConfig_To_v1alpha1_RAIDConfig(in *v1beta1.RAIDConfig, out *RAIDConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_RAIDConfig_To_v1alpha1_RAIDConfig(in, out, s)
}

func autoConvert_v1alpha1_RebootAnnotationArguments_To_v1beta1_RebootAnnotationArguments(in *RebootAnnotationArguments, out *v1beta1.RebootAnnotationArguments, s conversion.Scope) error {
	out.Mode = v1beta1.RebootMode(in.Mode)
	out.Force = in.Force
	return nil
}

// Convert_v1alpha1_RebootAnnotationArguments_To_v1beta1_RebootAnnotationArguments is an autogenerated conversion function.
func Convert_v1alpha1_RebootAnnotationArguments_To_v1beta1_RebootAnnotationArguments(in *RebootAnnotationArguments, out *v1beta1.RebootAnnotationArguments, s conversion.Scope) error {
	return autoConvert_v1alpha1_RebootAnnotationArguments_To_v1beta1_RebootAnnotationArguments(in, out, s)
}

func autoConvert_v1beta1_RebootAnnotationArguments_To_v1alpha1_RebootAnnotationArguments(in *v1beta1.RebootAnnotationArguments, out *RebootAnnotationArguments, s conversion.Scope) error {
	out.Mode = RebootMode(in.Mode)
	out.Force = in.Force
	return nil
}

// Convert_v1beta1_RebootAnnotationArguments_To_v1alpha1_RebootAnnotationArguments is an autogenerated conversion function.
func Convert_v1beta1_RebootAnnotationArguments_To_v1alpha1_RebootAnnotationArguments(in *v1beta1.RebootAnnotationArguments, out *RebootAnnotationArguments, s conversion.Scope) error {
	return autoConvert_v1beta1_RebootAnnotationArguments_To_v1alpha1_RebootAnnotationArguments(in, out, s)
}

func autoConvert_v1alpha1_RootDeviceHints_To_v1beta1_RootDeviceHints(in *RootDeviceHints, out *v1beta1.RootDeviceHints, s conversion.Scope) error {
	out.DeviceName = in.DeviceName
	out.HCTL = in.HCTL
	out.Model = in.Model
	out.Vendor = in.Vendor
	out.SerialNumber = in.SerialNumber
	out.MinSizeGigabytes = in.MinSizeGigabytes
	out.WWN = in.WWN
	out.WWNWithExtension = in.WWNWithExtension
	out.WWNVendorExtension = in.WWNVendorExtension
	out.Rotational = (*bool)(unsafe.Pointer(in.Rotational))
	return nil
}

// Convert_v1alpha1_RootDeviceHints_To_v1beta1_RootDeviceHints is an autogenerated conversion function.
func Convert_v1alpha1_RootDeviceHints_To_v1beta1_RootDeviceHints(in *RootDeviceHints, out *v1beta1.RootDeviceHints, s conversion.Scope) error {
	return autoConvert_v1alpha1_RootDeviceHints_To_v1beta1_RootDeviceHints(in, out, s)
}

func autoConvert_v1beta1_RootDeviceHints_To_v1alpha1_RootDeviceHints(in *v1beta1.RootDeviceHints, out *RootDeviceHints, s conversion.Scope) error {
	out.DeviceName = in.DeviceName
	out.HCTL = in.HCTL
	out.Model = in.Model
	out.Vendor = in.Vendor
	out.SerialNumber = in.SerialNumber
	out.MinSizeGigabytes = in.MinSizeGigabytes
	out.WWN = in.WWN
	out.WWNWithExtension = in.WWNWithExtension
	out.WWNVendorExtension = in.WWNVendorExtension
	out.Rotational = (*bool)(unsafe.Pointer(in.Rotational))
	return nil
}

// Convert_v1beta1_RootDeviceHints_To_v1alpha1_RootDeviceHints is an autogenerated conversion function.
func Convert_v1beta1_RootDeviceHints_To_v1alpha1_RootDeviceHints(in *v1beta1.RootDeviceHints, out *RootDeviceHints, s conversion.Scope) error {
	return autoConvert_v1beta1_RootDeviceHints_To_v1alpha1_RootDeviceHints(in, out, s)
}

func autoConvert_v1alpha1_SoftwareRAIDVolume_To_v1beta1_SoftwareRAIDVolume(in *SoftwareRAIDVolume, out *v1beta1.SoftwareRAIDVolume, s conversion.Scope) error {
	out.RootVolume = in.RootVolume
	out.SizeGibibytes = (*int)(unsafe.Pointer(in.SizeGibibytes))
	out.Level = in.Level
	out.PhysicalDisks = *(*[]v1beta1.RootDeviceHints)(unsafe.Pointer(&in.PhysicalDisks))
	return nil
}

// Convert_v1alpha1_SoftwareRAIDVolume_To_v1beta1_SoftwareRAIDVolume is an autogenerated conversion function.
func Convert_v1alpha1_SoftwareRAIDVolume_To_v1beta1_SoftwareRAIDVolume(in *SoftwareRAIDVolume, out *v1beta1.SoftwareRAIDVolume, s conversion.Scope) error {
	return autoConvert_v1alpha1_SoftwareRAIDVolume_To_v1beta1_SoftwareRAIDVolume(in, out, s)
}

func autoConvert_v1beta1_SoftwareRAIDVolume_To_v1alpha1_SoftwareRAIDVolume(in *v1beta1.SoftwareRAIDVolume, out *SoftwareRAIDVolume, s conversion.Scope) error {
	out.RootVolume = in.RootVolume
	out.SizeGibibytes = (*int)(unsafe.Pointer(in.SizeGibibytes))
	out.Level = in.Level
	out.PhysicalDisks = *(*[]RootDeviceHints)(unsafe.Pointer(&in.PhysicalDisks))
	return nil
}

// Convert_v1beta1_SoftwareRAIDVolume_To_v1alpha1_SoftwareRAIDVolume is an autogenerated conversion function.
func Convert_v1beta1_SoftwareRAIDVolume_To_v1alpha1_SoftwareRAIDVolume(in *v1beta1.SoftwareRAIDVolume, out *SoftwareRAIDVolume, s conversion.Scope) error {
	return autoConvert_v1beta1_SoftwareRAIDVolume_To_v1alpha1_SoftwareRAIDVolume(in, out, s)
}

func autoConvert_v1alpha1_Storage_To_v1beta1_Storage(in *Storage, out *v1beta1.Storage, s conversion.Scope) error {
	out.Name = in.Name
	out.AlternateNames = *(*[]string)(unsafe.Pointer(&in.AlternateNames))
	out.Rotational = in.Rotational
	out.Type = v1beta1.DiskType(in.Type)
	out.SizeBytes = v1beta1.Capacity(in.SizeBytes)
	out.Vendor = in.Vendor
	out.Model = in.Model
	out.SerialNumber = in.SerialNumber
	out.WWN = in.WWN
	out.WWNVendorExtension = in.WWNVendorExtension
	out.WWNWithExtension = in.WWNWithExtension
	out.HCTL = in.HCTL
	return nil
}

// Convert_v1alpha1_Storage_To_v1beta1_Storage is an autogenerated conversion function.
func Convert_v1alpha1_Storage_To_v1beta1_Storage(in *Storage, out *v1beta1.Storage, s conversion.Scope) error {
	return autoConvert_v1alpha1_Storage_To_v1beta1_Storage(in, out, s)
}

func autoConvert_v1beta1_Storage_To_v1alpha1_Storage(in *v1beta1.Storage, out *Storage, s conversion.Scope) error {
	out.Name = in.Name
	out.AlternateNames = *(*[]string)(unsafe.Pointer(&in.AlternateNames))
	out.Rotational = in.Rotational
	out.Type = DiskType(in.Type)
	out.SizeBytes = Capacity(in.SizeBytes)
	out.Vendor = in.Vendor
	out.Model = in.Model
	out.SerialNumber = in.SerialNumber
	out.WWN = in.WWN
	out.WWNVendorExtension = in.WWNVendorExtension
	out.WWNWithExtension = in.WWNWithExtension
	out.HCTL = in.HCTL
	return nil
}

// Convert_v1beta1_Storage_To_v1alpha1_Storage is an autogenerated conversion function.
func Convert_v1beta1_Storage_To_v1alpha1_Storage(in *v1beta1.Storage, out *Storage, s conversion.Scope) error {
	return autoConvert_v1beta1_Storage_To_v1alpha1_Storage(in, out, s)
}

func autoConvert_v1alpha1_SwitchPortConfig_To_v1beta1_SwitchPortConfig(in *SwitchPortConfig, out *v1beta1.SwitchPortConfig, s conversion.Scope) error {
	out.Mode = v1beta1.SwitchPortMode(in.Mode)
	out.NativeVLAN = in.NativeVLAN
	out.AllowedVLANs = *(*[]int)(unsafe.Pointer(&in.AllowedVLANs))
	out.MTU = (*int)(unsafe.Pointer(in.MTU))
	return nil
}

// Convert_v1alpha1_SwitchPortConfig_To_v1beta1_SwitchPortConfig is an autogenerated conversion function.
func Convert_v1alpha1_SwitchPortConfig_To_v1beta1_SwitchPortConfig(in *SwitchPortConfig, out *v1beta1.SwitchPortConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_SwitchPortConfig_To_v1beta1_SwitchPortConfig(in, out, s)
}

func autoConvert_v1beta1_SwitchPortConfig_To_v1alpha1_SwitchPortConfig(in *v1beta1.SwitchPortConfig, out *SwitchPortConfig, s conversion.Scope) error {
	out.Mode = SwitchPortMode(in.Mode)
	out.NativeVLAN = in.NativeVLAN
	out.AllowedVLANs = *(*[]int)(unsafe.Pointer(&in.AllowedVLANs))
	out.MTU = (*int)(unsafe.Pointer(in.MTU))
	return nil
}

// Convert_v1beta1_SwitchPortConfig_To_v1alpha1_SwitchPortConfig is an autogenerated conversion function.
func Convert_v1beta1_SwitchPortConfig_To_v1alpha1_SwitchPortConfig(in *v1beta1.SwitchPortConfig, out *SwitchPortConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_SwitchPortConfig_To_v1alpha1_SwitchPortConfig(in, out, s)
}

func autoConvert_v1alpha1_SwitchPortIdentifier_To_v1beta1_SwitchPortIdentifier(in *SwitchPortIdentifier, out *v1beta1.SwitchPortIdentifier, s conversion.Scope) error {
	out.SwitchID = in.SwitchID
	out.PortID = in.PortID
	out.SwitchSystemName = in.SwitchSystemName
	return nil
}

// Convert_v1alpha1_SwitchPortIdentifier_To_v1beta1_SwitchPortIdentifier is an autogenerated conversion function.
func Convert_v1alpha1_SwitchPortIdentifier_To_v1beta1_SwitchPortIdentifier(in *SwitchPortIdentifier, out *v1beta1.SwitchPortIdentifier, s conversion.Scope) error {
	return autoConvert_v1alpha1_SwitchPortIdentifier_To_v1beta1_SwitchPortIdentifier(in, out, s)
}

func autoConvert_v1beta1_SwitchPortIdentifier_To_v1alpha1_SwitchPortIdentifier(in *v1beta1.SwitchPortIdentifier, out *SwitchPortIdentifier, s conversion.Scope) error {
	out.SwitchID = in.SwitchID
	out.PortID = in.PortID
	out.SwitchSystemName = in.SwitchSystemName
	return nil
}

// Convert_v1beta1_SwitchPortIdentifier_To_v1alpha1_SwitchPortIdentifier is an autogenerated conversion function.
func Convert_v1beta1_SwitchPortIdentifier_To_v1alpha1_SwitchPortIdentifier(in *v1beta1.SwitchPortIdentifier, out *SwitchPortIdentifier, s conversion.Scope) error {
	return autoConvert_v1beta1_SwitchPortIdentifier_To_v1alpha1_SwitchPortIdentifier(in, out, s)
}

func autoConvert_v1alpha1_VLAN_To_v1beta1_VLAN(in *VLAN, out *v1beta1.VLAN, s conversion.Scope) error {
	out.ID = v1beta1.VLANID(in.ID)
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_VLAN_To_v1beta1_VLAN is an autogenerated conversion function.
func Convert_v1alpha1_VLAN_To_v1beta1_VLAN(in *VLAN, out *v1beta1.VLAN, s conversion.Scope) error {
	return autoConvert_v1alpha1_VLAN_To_v1beta1_VLAN(in, out, s)
}

func autoConvert_v1beta1_VLAN_To_v1alpha1_VLAN(in *v1beta1.VLAN, out *VLAN, s conversion.Scope) error {
	out.ID = VLANID(in.ID)
	out.Name = in.Name
	return nil
}

// Convert_v1beta1_VLAN_To_v1alpha1_VLAN is an autogenerated conversion function.
func Convert_v1beta1_VLAN_To_v1alpha1_VLAN(in *v1beta1.VLAN, out *VLAN, s conversion.Scope) error {
	return autoConvert_v1beta1_VLAN_To_v1alpha1_VLAN(in, out, s)
}
