apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ironic-cacert
spec:
  commonName: ironic-ca
  isCA: true
  ipAddresses:
  - IRONIC_HOST_IP
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: ironic-cacert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
spec:
  ca:
    secretName: ironic-cacert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ironic-cert
spec:
  commonName: ironic-cert
  ipAddresses:
  - IRONIC_HOST_IP
  issuerRef:
    kind: Issuer
    name: ca-issuer
  secretName: ironic-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ironic-inspector-cert
spec:
  commonName: ironic-inspector-cert
  ipAddresses:
  - IRONIC_HOST_IP
  issuerRef:
    kind: Issuer
    name: ca-issuer
  secretName: ironic-inspector-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mariadb-cert
spec:
  commonName: mariadb-cert
  ipAddresses:
  - MARIADB_HOST_IP
  issuerRef:
    kind: Issuer
    name: ca-issuer
  secretName: mariadb-cert
