FROM registry.hub.docker.com/library/golang:1.14

ENV SDK_VERSION=v0.17.0
ENV SDK_BIN=/sdkbin
ENV PATH="${SDK_BIN}:${PATH}"

RUN mkdir -p ${SDK_BIN}

# Install a stable build of operator-sdk
ADD https://github.com/operator-framework/operator-sdk/releases/download/${SDK_VERSION}/operator-sdk-${SDK_VERSION}-x86_64-linux-gnu ${SDK_BIN}/operator-sdk
RUN chmod 0755 ${SDK_BIN}/operator-sdk

# Install kube-openapi from source
RUN mkdir -p ${GOPATH}/src/github.com/kubernetes && cd ${GOPATH}/src/github.com/kubernetes && git clone https://github.com/kubernetes/kube-openapi && cd kube-openapi && go install ./cmd/...

LABEL io.k8s.display-name="Metal3 operator-sdk test image" \
      io.k8s.description="This image is for running tests requiring the operator-sdk"
