ARG OVERRIDE_DOCKER_HUB_REGISTRY=${OVERRIDE_DOCKER_HUB_REGISTRY:-"registry.hub.docker.com"}

FROM "${OVERRIDE_DOCKER_HUB_REGISTRY}"/library/golang:1.15.3

RUN go get -u golang.org/x/lint/golint

LABEL io.k8s.display-name="Metal3 golint test image" \
      io.k8s.description="This image is for running tests requiring golint"
