apiVersion: apps/v1
kind: Deployment
metadata:
  name: metal3-baremetal-operator
spec:
  template:
    spec:
      containers:
      # Change the value of image field below to your controller image URL
      - image: gcr.io/arvinders-1st-project/baremetal-operator-amd64:dev
        name: baremetal-operator
