apiVersion: metal3.io/v1alpha1
kind: FirmwareSchema
metadata:
  name: firmwareschema-sample
spec:
status:
  referenceCount: 2
  hardwareVendor: "VendorA"
  hardwareModel: "ModelT"
  schema:
    - "ProcVirtualization":
         attributeType: "Enumeration"
         allowableValues:
           - "Enabled"
           - "Disabled"
         readOnly: false
    - "ProcCPUCores":
         attributeType: "Integer"
         lowerBound: 1
         readOnly: true
         upperBound: 100
    - "SRIOV":
         allowableValues:
           - "Enabled"
           - "Disabled"
    - "SystemModelName":
         attributeType: "String"
         maxLength: 40
         minLength: 0
         readOnly: true
    - "SerialNumber":
         attributeType: "String"
         maxLength: 16
         minLength: 0
