apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../rbac
- ../crds
- ../operator/no_ironic
configMapGenerator:
- envs:
  - ironic_bmo_configmap.env
  name: ironic-bmo-configmap