apiVersion: apps/v1
kind: Deployment
metadata:
  name: ironic
spec:
  template:
    spec:
      containers:
      - name: ironic
        envFrom:
        - configMapRef:
            name: ironic-bmo-configmap
        volumeMounts:
        - name: ironic-htpasswd
          mountPath: "/auth/ironic"
          readOnly: true
      volumes:
      # This is the htpassword matching the ironic password
      - name: ironic-htpasswd
        secret:
          secretName: ironic-htpasswd
