apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- ./automated-cleaning
- ./basic-ops
- ./external-inspection
- ./externally-provisioned
- ./inspection
- ./live-iso-ops
- ./provisioning-ops
- ./re-inspection

patches:
# Remove ClusterRoleBinding (namaspace scoped mode)
- patch: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: baremetal-operator-manager-rolebinding
    $patch: delete
# Remove ClusterRole (namaspace scoped mode)
- patch: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: baremetal-operator-manager-role
    $patch: delete
- path: ./namespaced-manager-patch.yaml
