apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metal3
resources:
- ../../namespace
- ../../rbac
- ../../crds
- ../../deployments/bmo
configMapGenerator:
- envs:
  - ironic_bmo_configmap.env
  name: ironic-bmo-configmap