name: build-fork-image

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
    - 'starlark'

jobs:
  build_bmo:
    name: Build and push fork BMO image to GHCR
    if: github.repository != 'metal3-io/baremetal-operator'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        persist-credentials: false

    - name: Calculate Go version
      id: vars
      run: echo "go_version=$(make go-version)" >> "$GITHUB_OUTPUT"

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ steps.vars.outputs.go_version }}

    - name: Log in to GHCR
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build image
      run: make docker-build
      env:
        REGISTRY: ghcr.io/${{ github.repository_owner }}
        IMG_TAG: ${{ github.ref_name }}

    - name: Push image
      run: docker push ghcr.io/${{ github.repository_owner }}/baremetal-operator-amd64:${{ github.ref_name }}
