name: E2E Test

on:
  workflow_call:
    inputs:
      bmc-protocol:
        required: true
        type: string
      runner:
        type: string
        default: "oracle-vm-4cpu-16gb-x86-64"
      ginkgo-focus:
        type: string
        default: ""
      ref:
        type: string
        default: ${{ github.ref }}
      timeout-minutes:
        type: number
        default: 90

permissions: {}

jobs:
  test:
    name: E2E test
    runs-on: ${{ inputs.runner }}
    timeout-minutes: ${{ inputs.timeout-minutes }}

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        ref: ${{ inputs.ref }}
        persist-credentials: false

    - name: Install libvirt
      run: |
        sudo apt-get update
        sudo apt-get install -y libvirt-daemon-system qemu-kvm virt-manager libvirt-dev

    - name: Disable containerd image store (Docker 29 workaround)
      # See: https://github.com/kubernetes-sigs/kind/issues/3795
      # See: https://github.com/actions/runner-images/issues/13474
      run: |
        echo '{"features":{"containerd-snapshotter":false}}' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker

    - name: Run BMO e2e Tests
      env:
        BMC_PROTOCOL: ${{ inputs.bmc-protocol }}
        GINKGO_FOCUS: "${{ inputs.ginkgo-focus }}"
      # We need a new shell to pick up the new group. That is why we do the sudo -s -u $USER ...
      # Remove the pre-installed go version. We install the exact version we need.
      run: |
        sudo usermod -a -G libvirt $USER
        sudo rm /usr/bin/go
        sudo -s -u $USER --preserve-env bash ${{ github.workspace }}/hack/ci-e2e.sh

    - name: Upload artifacts
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: artifacts-${{ inputs.bmc-protocol }}.tar.gz
        path: test/e2e/_artifacts
        if-no-files-found: error
        overwrite: false
