name: unit

on:
  workflow_call:


permissions: {}

jobs:
  unit-tests:
    name: unit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT
    - name: Set up Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - name: Run unit tests
      run: make -e unit-cover
      env:
        TEST_FLAGS: "-v"
