name: unit

on:
  workflow_call:


permissions: {}

jobs:
  unit-tests:
    name: unit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false
    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT
    - name: Set up Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - name: Run unit tests
      run: make -e unit-cover
      env:
        TEST_FLAGS: "-v"
    - name: Install libvirt-dev
      run: sudo apt-get update && sudo apt-get install -y libvirt-dev
    - name: Run vbmctl unit tests
      run: make -e unit-vbmctl
      env:
        TEST_FLAGS: "-v"
