name: verify-e2e-checksums

on:
  workflow_call:

permissions: {}

jobs:
  verify-e2e-checksums:
    name: verify-e2e-checksums
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Verify E2E checksums are up to date
      run: make verify-e2e-checksums
